### ISSUE TITLE
[Feature Request] Student selector in anonymous login

### ISSUE THREAD

**Issue by 7RST1** [SapuSeven/BetterUntis#101]
Currently, the app relies on the user logging in to get their personal timetable. Our school does not allow login, but has a list where you can chose your name.(see picture below)

Therefore it would be nice to have a option to get the student names and choose a timetable even though you're anonymously connected on the app. Could be useful even when you are logged in to see friends' timetables.

<details>
  <summary><b>WebUntis student selector image</b></summary>
  
  ![Skjermdump fra 2020-08-16 23-15-34](https://user-images.githubusercontent.com/16783057/90344192-8b0d5d80-e017-11ea-9766-72a968869bcb.png)

</details>

**Comment by 7RST1** [comment]
Just realized the official app doesn't have this feature, and the API between web and app might be different. Is it still possible to add?

**Comment by SapuSeven** [comment]
BetterUntis relies on analyzing the Untis API by observing the original app. If Untis Mobile never uses an API endpoint, BetterUntis also can't use it.
So usually this would be an API restriction.

However, it is possible to request a timetable using a different Student ID, but I have no idea where to get those IDs.

So until someone finds a way to get student names and IDs from the API, I don't think this is possible.

**Comment by 7RST1** [comment]
Okay. I did e-mail the Untis developers about this, and they said they would forward it to the developer team. Hopefully they will implement it in the official app, so that the API will get updated. Never know if they actually listen tho. Will assume impossible to add till then. If they actually do implement it in the official app and/or I get further response from them, I'll update this issue.
