### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by TobiFlobi26** [SapuSeven/BetterUntis#105]
[logs-1598420148630.zip](https://github.com/SapuSeven/BetterUntis/files/5127789/logs-1598420148630.zip)
[logs-1598420122428.zip](https://github.com/SapuSeven/BetterUntis/files/5127790/logs-1598420122428.zip)

<details>
<summary>Crash Log</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu. 
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1598420148630.zip`
```
</details>

**Comment by SapuSeven** [comment]
Sorry, there was a mistake publishing the latest release (3.3.2).
I just published the new version on the play store (3.3.3), it should fix the issue and allow you opening the info center again.
