### ISSUE TITLE
[Question] Can the APP also be used as a student? I dont see  "Stundenplan"

### ISSUE THREAD

**Issue by gitpower2017** [SapuSeven/BetterUntis#110]
Can the APP also be used as a student? I dont see "Stundenplan"

I use the QR Code from WebUntis.
In WebUntis the login data works.
In BetterUntis I see nothing.

I see Klassroom Pulldown menu.

I have general login data for students

**Comment by SapuSeven** [comment]
You should be able to use the app as a student.
When you first open the app, you can login using the QR code.
After that, you should see your personal timetable.
If you want to view another timetable you have to open the drawer (swipe from the left edge) and select "Teachers", "Classes" or "Rooms". Then another window pops up where you can select the desired element.

**Comment by SapuSeven** [comment]
Closing as no response for about a month. Feel free to reopen if there are any more questions.
