### ISSUE TITLE
[Feature Request] Local Database

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#119]
**Describe the solution you'd like**

Ability to add, edit and delete own local homework and exams.

<details>
  <summary><b>Additional context</b></summary>

  Maybe a floating action button in the info center to add, or long pressing a subject for an "actions" menu. 

Second local database with all the info needed.
</details>

**Comment by Ordoviz** [comment]
Is somebody working on this? BetterUntis knows one’s timetable and cancelled lessons making it possible to sort homework by due date. A simple todo app cannot do this.

I am willing to help but don’t know whether I can.

**Comment by Pleezon** [comment]
I'd also be interested in this feature.

**Comment by SapuSeven** [comment]
Planned, but currently not worked on - see #304
