### ISSUE TITLE
Color of cancelled lessons when using school color scheme

### ISSUE THREAD

**Issue by k1ba-meow** [SapuSeven/BetterUntis#12]
Cancelled lessons have no color assigned by the school, so you should still be able to set a color for them if the school color  scheme is used (i.e. the option to do so shouldn't be disabled)

**Comment by SapuSeven** [comment]
Working on it - I'll add an option to use school colors separately for irregular or cancelled lessons.

**Comment by SapuSeven** [comment]
Implemented in dda24a39dfb73341157bbbc99cc76ce33dab7233 ([build#90](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=90))
