### ISSUE TITLE
[Feature Request] Changeable name in Time table ("Eigener Stundenplan") 

### ISSUE THREAD

**Issue by maidado** [SapuSeven/BetterUntis#120]
Locally changeable student name that is visible in top bar in Timetable ("Eigener Stundenplan") (Red circled) only locally (like not changing it online. Only locally so that teachers don't see) would be very nice

Open for questions
![1959](https://user-images.githubusercontent.com/43068155/93932532-a65b3f00-fd20-11ea-8d87-218439d7582a.png)

**Comment by SapuSeven** [comment]
Silly question: Why would you want to be able to do that?

**Comment by Domi04151309** [comment]
I actually think renaming profiles is more useful.

**Comment by maidado** [comment]
> Silly question: Why would you want to be able to do that?

Some probably.. have their reason...

**Comment by maidado** [comment]
> I actually think renaming profiles is more useful.

Yeah that would be nice

**Comment by DreamyLynn** [comment]
I made a similar fuctionality for my own usage. Because I only need it for myself and don't think it'd be useful for most people it's a hacky, hard-coded one, but I'd love to redo it properly if that's okay with you, @SapuSeven . If you, @maidado, want to use mine for now, please tell me and I'll give you the source code.

**Comment by maidado** [comment]
> I made a similar fuctionality for my own usage. Because I only need it for myself and don't think it'd be useful for most people it's a hacky, hard-coded one, but I'd love to redo it properly if that's okay with you, @SapuSeven . If you, @maidado, want to use mine for now, please tell me and I'll give you the source code.

I replaced it with a hardcoded string with my.. preferred Name in the source so.. yea...


But would be nice if it would be an actual feature!

**Comment by SapuSeven** [comment]
Hi there,
@x5nake it would be awesome if you could work on an implementation for that. Feel free to open a new wip pull request for any questions or discussions. I'm happy to help you out as I don't have much time available to work on it myself.

**Comment by SapuSeven** [comment]
Implemented in #173 by allowing to change profile names and already published (v3.4.6 I think).
