### ISSUE TITLE
[Crash Report] Crash when viewing timetable lesson info

### ISSUE THREAD

**Issue by maidado** [SapuSeven/BetterUntis#121]
[logs-1601049154749.zip](https://github.com/SapuSeven/BetterUntis/files/5283866/logs-1601049154749.zip)

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.0 (24)_
- Installation source: _com.android.vending_

**Comment by maidado** [comment]
Clicking an item in the Schedule makes the app crash

**Comment by SapuSeven** [comment]
Thanks for the report.

I just identified the issue and I'm already working on a fix.

**Comment by SapuSeven** [comment]
Fixed in v3.4.1

~~Google Play usually takes a while to publish new updates, so you may need to wait a few days for the update or directly download the APK [from the Releases page](https://github.com/SapuSeven/BetterUntis/releases/tag/v3.4.1).~~

EDIT: Update is now live on Google Play.
