### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by Produce2727** [SapuSeven/BetterUntis#122]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1601132602962.zip`
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.0 (24)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Thanks for the report.
See #121 for updates.
