### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by Klausmd5** [SapuSeven/BetterUntis#125]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1601204411760.zip`
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.1 (25)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
You need to add the log files (saved at `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1601204411760.zip`).

I suspect this is the same as #124?

**Comment by Klausmd5** [comment]
yeah could be.. this happened after updating. The errorscreen showed up after opening the app. Clearing cache removed the screen and now it works.. I think the error was just cached from the previous Version..

**Comment by SapuSeven** [comment]
Alright, I think this is resolved then.
Later versions should be more stable.
