### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by Produce2727** [SapuSeven/BetterUntis#126]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1601266946773.zip`
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.1 (25)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
So.... Can you upload the log files?

**Comment by Produce2727** [comment]
Am 28.09.2020 06:24 schrieb SapuSeven <notifications@github.com>:
So.... Can you upload the log files?

**Comment by SapuSeven** [comment]
Please check the new version 3.4.3 that just released and see if it still crashes.
