### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by kescherCode** [SapuSeven/BetterUntis#128]
<details>
<summary>Logs</summary>

```
Please attach the compressed log files to this issue.
They have been saved to `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1601497465062.zip`
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.1 (25)_
- Installation source: _org.fdroid.fdroid.privileged_
[logs-1601497465062.zip](https://github.com/SapuSeven/BetterUntis/files/5308097/logs-1601497465062.zip)

**Comment by kescherCode** [comment]
Log is attached at the bottom, sorry!

**Comment by SapuSeven** [comment]
That seems odd.. the uploaded zip does not contain any logs

Can you explain how this crash happened?

**Comment by kescherCode** [comment]
@SapuSeven Sure.

I pressed on a lesson marked as substitutes. It has two teachers assigned to it, both of which are not present. In the table view, I only see a "?" symbol. When I click on it, I briefly see a view with the usual teachers striked through, followed by a crash.

I'm assuming it's some kind of unexpected null value in the JSON the app receives, since no substitute is assigned to said lesson, yet it is marked as a lesson with substitutes.

**Comment by SapuSeven** [comment]
Ok, I have two ideas you could try.

First, clear the application cache from the Android system settings.
If that doesn't help, try re-logging into your profile (open the drawer, tap on your profile, long-press your profile in the dropdown list, login).

**Comment by kescherCode** [comment]
@SapuSeven I cleared the app's data. Crash still happens on new login.

For easier debugging, is there a way I could safely share my credentials with you? I'm sure that would be the most useful way for you to debug this.

**Comment by SapuSeven** [comment]
Ok, first please check the new version 3.4.3 that just released and see if it still crashes.

**Comment by kescherCode** [comment]
Version 3.4.3 fixes the issue, thank you!
