### ISSUE TITLE
Overlapping times

### ISSUE THREAD

**Issue by SimonIT** [SapuSeven/BetterUntis#13]
As you can see in the bottom left corner of the screenshot, the times and the number for the 15th lesson are not readable.
![Screenshot_1572464493](https://user-images.githubusercontent.com/11720038/67893482-f3598400-fb56-11e9-8b7b-796fd89b0069.png)

**Comment by SapuSeven** [comment]
Thanks for reporting.
Can you share your school id so I can check using anonymous login?

**Comment by SimonIT** [comment]
2498900

**Comment by SapuSeven** [comment]
Fixed in 6cf2b2931a8879fdf6cfed8a52ef4eceb0c85750 ([build#96](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=96)).
