### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by timhorn1** [SapuSeven/BetterUntis#139]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1601843809218.zip`
```
</details>

**Additional information**

- Android version: _9_
- BetterUntis version: _3.4.1 (25)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
This has probably been resolved in version 3.4.3. Please update the app and test it again.
