### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by KungFuCrafter** [SapuSeven/BetterUntis#140]
>  @`<details>`

<summary>Logs</summary>

```
Please attach the compressed log files to this issue.
They have been saved to `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1601931241857.zip`
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.1 (25)_
- Installation source: _com.google.android.packageinstaller_
[logs-1601931241857.zip](https://github.com/SapuSeven/BetterUntis/files/5330040/logs-1601931241857.zip)

**Comment by SapuSeven** [comment]
Please update to the latest version before submitting a crash report.
