### ISSUE TITLE
[Bug Report] Deleting Profiles

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#142]
**Description**

_Deleting a profile does not delete the preferences associated with the profile, resulting in a new profile adopting the settings of the old profile._

**Comment by SapuSeven** [comment]
I see...
SQLite internally uses `rowid` when a column is specified as `PRIMARY KEY`, which is the case for the profile id. However, these integers get reused, so it'd also be possible to define the column as `AUTOINCREMENT` to prevent this.

**Comment by Domi04151309** [comment]
But since the preferences for each profile are defined in separate files it would also be possible to just delete that specific file when the profile gets deleted.

**Comment by SapuSeven** [comment]
Hang on... Profile preferences should already be deleted (see 7e413b3ec564d3bd272e3844f6ceef38c7ae12f7). Not sure why it's not working.

**Comment by SapuSeven** [comment]
This will be fixed with the Material 3 Update (#290).
