### ISSUE TITLE
[Bug Report] Multiple homeworks for single lesson

### ISSUE THREAD

**Issue by SapuSeven** [SapuSeven/BetterUntis#144]
**Description**

If a lesson has multiple homeworks, only the first one is displayed. Every following one is empty.

<details>
  <summary><b>Details</b></summary>

This is caused by [TimetableItemDetailsFragment.kt](https://github.com/SapuSeven/BetterUntis/blob/82a9edfaf074897c220e8e26b0812b6aba743620/app/src/main/java/com/sapuseven/untis/fragments/TimetableItemDetailsFragment.kt#L98-L105) adding the same layout multiple times using inflation, which produces duplicated ids for the `TextView`s.

A possible solution would be to transition the item details dialog to use a `ListView` or similar, but this would complicate things a bit.
</details>

**Additional information**

 - BetterUntis version: _3.4.3 (27)_

**Comment by Domi04151309** [comment]
I think you can inflate the layout multiple times so that it is a different root layout every time.
Maybe using the Cloneable class to clone the layout is a faster approach.

**Comment by Domi04151309** [comment]
I'll look into this.

**Comment by Domi04151309** [comment]
As to why this happened:
The inflated element was attached to the root layout before the text was set so that every next item's text wasn't settable because the id already existed. By attaching the layout to the parent view after setting its text the ids are unique again and setting the text works.

**Comment by SapuSeven** [comment]
Fixed.
