### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by DerBraky** [SapuSeven/BetterUntis#145]
<details>
<summary>Logs</summary>

```
[logs-1602106114315.zip](https://github.com/SapuSeven/BetterUntis/files/5343948/logs-1602106114315.zip)
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.1 (25)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
This has probably been resolved in version 3.4.3. Please update the app and test it again.
