### ISSUE TITLE
[Bug Report] App crashes when adding a profile

### ISSUE THREAD

**Issue by avtkal** [SapuSeven/BetterUntis#149]
**Description**

BetterUntis crashes when I try to add an anonymous profile. I know my school supports anonymous login because I had my timetable in BetterUntis some weeks ago.

- Open BetterUntis
- Add my school (Universidad del Pais Vasco)
- Click on _login_
- App crashes all over again

**Additional information**

 - Android version: _7.1.2_
 - BetterUntis version: _3.4.3_
 - Installation source: _F-Droid_

**Comment by SapuSeven** [comment]
Similar to #124
Thanks for reporting, this will be addressed soon.

**Comment by prefectAtEarth** [comment]
EDIT: moved this to another Issue: #150 
Xiaomi MiA2Lite
Android 10
Version 3.4.1 from F-Droid
Cannot provide Logfile as there is none, neither in my device nor the emulator.
Cloned the repo. After logging in with valid user (tried with emulator Pixel 3a API29 and mentioned device) the app crashes on startup. Clearing cache doesn't help.
Could track down crash, in my case, to UserDatabase.kt, line 185
```kotlin
getJSON().parse(UntisUserData.serializer(), cursor.getString(cursor.getColumnIndex(UserDatabaseContract.Users.COLUMN_NAME_USERDATA)))
```
Top of Logcat from AndroidStudio:
```Log
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sapuseven.untis.debug/com.sapuseven.untis.activities.MainActivity}: kotlinx.serialization.json.JsonDecodingException: Unexpected JSON token at offset 131: Unexpected leading comma.
     JSON input: ....."departmentId":0,"children":[,],"klassenIds":[],"rights":["C.....
```
I'm not sure what the Serializer is expecting. Hope this helps.

**Comment by avtkal** [comment]
After some weeks using BetterUntis again, I do not have any problem with the anonymous login now. I have been adding various profiles these days and everything seems fine.
