### ISSUE TITLE
[Crash Report] Crash after Login with credentials with more than one child on same account

### ISSUE THREAD

**Issue by prefectAtEarth** [SapuSeven/BetterUntis#150]
Xiaomi MiA2Lite
Android 10
Version 3.4.1 from F-Droid
Cannot provide Logfile as there is none, neither in my device nor the emulator.
Cloned the repo. After logging in with valid user (tried with emulator Pixel 3a API29 and mentioned device) the app crashes on startup. Clearing cache doesn't help.
Could track down crash, in my case, to UserDatabase.kt, line 185
```kotlin
getJSON().parse(UntisUserData.serializer(), cursor.getString(cursor.getColumnIndex(UserDatabaseContract.Users.COLUMN_NAME_USERDATA)))
```
Top of Logcat from AndroidStudio:
```Log
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sapuseven.untis.debug/com.sapuseven.untis.activities.MainActivity}: kotlinx.serialization.json.JsonDecodingException: Unexpected JSON token at offset 131: Unexpected leading comma.
     JSON input: ....."departmentId":0,"children":[,],"klassenIds":[],"rights":["C.....
```
I'm not sure what the Serializer is expecting. Hope this helps.

_Originally posted by @prefectAtEarth in https://github.com/SapuSeven/BetterUntis/issue_comments/710798522_

**Comment by SapuSeven** [comment]
Did you change anything in the logs you provided or is the response from the server literally invalid JSON (`"children":[,]`)?

**Comment by prefectAtEarth** [comment]
Sorry for letting you wait.
No, I didn't change anything. But I don't think it's from the server. It seems more like it crashes when trying to read from the app's internal database. Maybe there's something wrong when saving to the database.
What I saw the app gets a valid json from the server. When parsing from json to object there seems to be something wrong if the "children" field is a list/array and not a single value. Therefor it cannot be saved as expected to the sqlite db. When reading again it fails with the error above (but that's all just a guess, I'm not really sure about it but your Serialization Implementation is really cool).

**Comment by SapuSeven** [comment]
Finally figured this one out. Should be fixed in the next release.
