### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by x653** [SapuSeven/BetterUntis#154]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 0
Fehlercode: 2
Fehlermeldung: unexpected end of stream on Connection{mobile.webuntis.com:443, proxy=DIRECT@ hostAddress=213.208.138.154 cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 protocol=http/1.1} (recycle count=2)
```
</details>

**Additional information**

- Android version: _6.0.1_
- BetterUntis version: _3.4.3-DEBUG (27)_
- Installation source: _(unknown)_

**Comment by SapuSeven** [comment]
Does this happen every time or just sometimes?

**Comment by SapuSeven** [comment]
Closing this as inactive and it seems like a network connectivity related issue.
