### ISSUE TITLE
[Crash Report] Crash when setting attendances

### ISSUE THREAD

**Issue by SirZuckerWahl** [SapuSeven/BetterUntis#155]
App stopped working, while placing attendance. 

<details>
<summary>Logs</summary>

[logs-1604564780737.zip](https://github.com/SapuSeven/BetterUntis/files/5512602/logs-1604564780737.zip)
[logs-1604946587426.zip](https://github.com/SapuSeven/BetterUntis/files/5512603/logs-1604946587426.zip)
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.3 (27)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
This should be fixed with the new Material 3 release as well.
