### ISSUE TITLE
[Feature Request] Teacher names

### ISSUE THREAD

**Issue by RedCommander735** [SapuSeven/BetterUntis#158]
**Describe the solution you'd like**

I'd like to suggest an option to be able to show the teachers names of the different lessons below the subject name.

**Comment by Domi04151309** [comment]
If I understand you correctly you suggest an option to switch the teacher and room labels? Currently, the teachers are on top and the rooms on the bottom.

**Comment by RedCommander735** [comment]
I was suggesting to add the teacher shorthand, maybe in the upper left corner of a lesson like this:

<img src="https://user-images.githubusercontent.com/40245965/177000087-803356f0-84e7-4e73-861c-728fe9133c7e.jpeg"  width="190" />

and the full name when you open the lesson on full-screen, like this:

<img src="https://user-images.githubusercontent.com/40245965/177000042-eaab6176-6d3d-417a-9582-d29fad0a1779.jpeg"  width="300" />

**Comment by Domi04151309** [comment]
That is already the case when Untis provides a teacher with your lesson, however teachers are only available on personal timetables and not on class timetables.

**Comment by RedCommander735** [comment]
That is somewhat weird, because in the official untis app it shows teacher shorthands for me when i click on the lessons in my personal timetable but not in betteruntis.
![Screenshot_20220702-191154.jpg](https://user-images.githubusercontent.com/40245965/177009994-ab2429f8-f58e-4125-b3db-a779142c8543.jpg)

**Comment by lm41** [comment]
Is this still an issue?

**Comment by RedCommander735** [comment]
for me it is

**Comment by SapuSeven** [comment]
Can you please try the following build I created and post the results of the timetable item details dialog?
https://output.circle-artifacts.com/output/job/dd613c8b-dc9a-4c69-8868-8e0e5aa62f60/artifacts/0/outputs/apk/debug/app-debug.apk

**Comment by EmilEmilchen** [comment]
Unfortunately this didnt work work for me, its still just the same.

**Comment by SapuSeven** [comment]
Can you please share a screenshot of the dialog after clicking on an item?

**Comment by EmilEmilchen** [comment]
Of course![Screenshot_20230215-100622_BetaUntis.png](https://user-images.githubusercontent.com/70268797/218984251-e23511a8-0e2d-460d-a25c-da314b53ca1b.png)

And how it looks in the UntisMobile App: 
![Screenshot_20230208-193407_Untis Mobile.png](https://user-images.githubusercontent.com/70268797/218984501-8057a858-79be-484d-adf5-ea77b2bfb147.png)

Edit: the "van Gee" is the teachers name

**Comment by SapuSeven** [comment]
Thanks
That's really strange...

**Comment by SapuSeven** [comment]
Seems to be connected to #328 - will continue this there.
