### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by x653** [SapuSeven/BetterUntis#159]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis.debug/files/logs-1606888314262.zip`
```
</details>

**Additional information**

- Android version: _6.0.1_
- BetterUntis version: _3.4.3-DEBUG (27)_
- Installation source: _(unknown)_

**Comment by x653** [comment]
just crashed?!

**Comment by SapuSeven** [comment]
Sorry to hear that.
Can you provide some more information as to how this happened?
Also can you upload the logs from your device (`/storage/emulated/0/Android/data/com.sapuseven.untis.debug/files/logs-1606888314262.zip`)?
