### ISSUE TITLE
Lesson topic is not available

### ISSUE THREAD

**Issue by techmaved** [SapuSeven/BetterUntis#164]
So I have this bug since the feature was implemented. I didn't know if this is only on my device so I hasitated to open a issue. [Pic](https://imgur.com/a/ZZjDq6i)

Android version: 10
BetterUntis version: 3.4.4 (28)

**Comment by SapuSeven** [comment]
Is the lesson topic shown correctly for the same lesson in the original untis app?

**Comment by techmaved** [comment]
@SapuSeven Yes, it is.

**Comment by Lauritz-Tieste** [comment]
I think this issue is inactive and the error should actually (if ever exists) be fixed. It works on my devices and the error would otherwise have been reported by other people. Therefore, the issue should be closed.

**Comment by SapuSeven** [comment]
I agree. Please reopen if it's still an issue in version 4.0.0.
