### ISSUE TITLE
[Bug Report] Lesson "0" not being displayed correctly

### ISSUE THREAD

**Issue by schm0lle** [SapuSeven/BetterUntis#166]
**Description**

My school has a lesson "zero" in its schedule, which is not used by my lesson plan.
BetterUntis shows it as the first lesson, so the real first one is displayed as the second and so on. This can be quite confusing, if you have a quick look on your schedule.

![Untis Mobile](https://user-images.githubusercontent.com/43651337/101688076-c2db5d80-3a6b-11eb-8f35-0b975fc4abbc.png)
![BetterUntis](https://user-images.githubusercontent.com/43651337/101688169-eb635780-3a6b-11eb-98bc-993ad3dd21f9.png)

**Additional information**

 - Android version: _SailfishOS with AlienDalvik 8.1.0_
 - BetterUntis version: _3.4.4 (28)_
 - Installation source: _F-Droid_

**Comment by DreamyLynn** [comment]
This has been fixed in 3.4.6
