### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by ghost** [SapuSeven/BetterUntis#167]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 2
Fehlercode: 2
Fehlermeldung: Unable to resolve host "mobile.webuntis.com": No address associated with hostname
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.4 (28)_
- Installation source: _com.aurora.adroid_

**Comment by SapuSeven** [comment]
Please check your network connectivity.
