### ISSUE TITLE
[Bug Report] A display issue

### ISSUE THREAD

**Issue by franklinbill** [SapuSeven/BetterUntis#168]
**Description**

_A clear and concise description of what the bug is.
Please add steps to reproduce the behavior._

In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text and the following EditText overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is 3.4.4, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.

_If your school supports anonymous login, you may also provide the school id for easier debugging._

<details>
  <summary><b>Screenshots</b></summary>
<img width="444" alt="bug-untis_28" src="https://user-images.githubusercontent.com/18572115/103148476-eb1cc900-479a-11eb-96a0-8f5d8cfe0a20.png">

  _Add screenshots here to describe the problem.
  Please include screenshots of the original Untis Mobile app if applicable._
</details>

<details>
  <summary><b>Logs</b></summary>

  _Add a detailed stack trace / crash log here if applicable._
</details>

**Additional information**

 - Android version: _System Settings -> About -> Android version (may differ on your device)_ Android 8.0
 - BetterUntis version: _Settings -> About -> App version_ 3.4.4
 - Installation source: _Google Play / F-Droid / SapuSeven.com / Own Build_ F-Droid

**Comment by SapuSeven** [comment]
Thanks for the feedback. This should be fixed with the Material 3 Update (#290).
