### ISSUE TITLE
[Bug Report] Properly handle network errors

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#169]
<details>
<summary>Logs</summary>

```
Request ID: 2
Error code: -32001
Error message: while handling mobile jsonrpc request
hint: Maybe target system is not running or unreachable?
method: 'getTimetable2017'
target webuntis: 'http://127.0.0.1/WebUntis/jsonrpc_intern.do?school=WHG+Durmersheim'
cause: java.lang.NullPointerException
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.3-DEBUG (27)_
- Installation source: _(unknown)_

**Comment by Lauritz-Tieste** [comment]
What exactly does this issue mean?

---

Note on the logs: maybe the server cannot be reached because 127.0.0.1 points to your OWN IP address and there is no server running there?

**Comment by SapuSeven** [comment]
This issue is about adding proper network error handling.
As it is a very old issue, this is probably obsolete.
If there's any need, please open a new issue.
