### ISSUE TITLE
[Feature Request] Detect irregular lessons

### ISSUE THREAD

**Issue by SimonIT** [SapuSeven/BetterUntis#17]
If we got teacher substitutions on our school, the lesson is purple with the colors of the school and the normal lessons are orange. With not using the colors provided by the school, all lessons with and without substitution have the same color. It would be nice if this substitutions would be detected as irregular. Maybe we can use the provided color for this

**Comment by SapuSeven** [comment]
Added in 21568588

**Comment by SimonIT** [comment]
Thank you, but it seem not to work for me
Without colors provided by my school:
![Screenshot_1573547809](https://user-images.githubusercontent.com/11720038/68655394-460c4600-0530-11ea-9e2c-012fb90b627d.png)
With colors provided by my school:
![Screenshot_1573547835](https://user-images.githubusercontent.com/11720038/68655397-46a4dc80-0530-11ea-89d5-b44ceb41f4fd.png)
My settings:
![Screenshot_1573547843](https://user-images.githubusercontent.com/11720038/68655399-46a4dc80-0530-11ea-99dd-a635837de94b.png)

**Comment by SapuSeven** [comment]
I see the issue. In my current implementation I check if teachers have changed from the original.
It seems you have no access to the teacher data, so I'll look into an implementation that also checks the background color.

**Comment by SimonIT** [comment]
Thank you!

**Comment by SapuSeven** [comment]
Please check if it works in 884b13ca ([build#124](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=124)). I added another setting for your case.

**Comment by SimonIT** [comment]
Works, thank you very much!
