### ISSUE TITLE
Updated translations not updated in code

### ISSUE THREAD

**Issue by avtkal** [SapuSeven/BetterUntis#171]
**Description**

_I updated Basque translation a few days ago on Weblate but it does not appear in the code yet. How and when are translations updated in general? Is there any automatic process?_

**Comment by SapuSeven** [comment]
There's a branch in the repository called `l10n_develop` which continuously gets updated by Weblate with the latest translations. Other changes generally go into the `develop` branch. If a new release is ready, all those branches are manually merged into `master` and the new version gets published automatically.

**Comment by avtkal** [comment]
Oh, I see now. Thank you!
