### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by pogpogcat** [SapuSeven/BetterUntis#176]
<details>
<summary>Logs</summary>

```
Please attach the compressed log files to this issue.
They have been saved to `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1613585390189.zip`
```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Please look at the issue text and upload the log files.
