### ISSUE TITLE
[Bug Report] Lesson 0 is labeled as lesson 1

### ISSUE THREAD

**Issue by luentien** [SapuSeven/BetterUntis#178]
![Screenshot_20210316-125353](https://user-images.githubusercontent.com/1869348/111305127-d7288b00-8656-11eb-9633-e259f1851240.png)

 - BetterUntis version: 3.4.5. (29)

**Comment by DreamyLynn** [comment]
duplicate of #166

**Comment by SapuSeven** [comment]
Thanks for reporting. This has been addressed in #172 and will be included in the next update.
