### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by mohnen** [SapuSeven/BetterUntis#179]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1616415582442.zip`
```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Please look at the issue text and upload the relevant log files.
