### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by SirZuckerWahl** [SapuSeven/BetterUntis#182]
[logs-1620718353171.zip](https://github.com/SapuSeven/BetterUntis/files/6457328/logs-1620718353171.zip)
 <details>

<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1620718353171.zip`
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
First, please try the latest version (3.5.1).
If the error still happens, please provide detailed steps to reproduce.
