### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Luisa080604** [SapuSeven/BetterUntis#183]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 20
Fehlercode: -8509
Fehlermeldung: no right for timetable
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Not a bug.
You are trying to view a timetable you have no permission for.
