### ISSUE TITLE
[Crash Report] App crashes when rotating device

### ISSUE THREAD

**Issue by CrackedMatter** [SapuSeven/BetterUntis#185]
The app crashes when rotating the device.
<details>
<summary>Logs</summary>

[logs-1624889476487.zip](https://github.com/SapuSeven/BetterUntis/files/6726949/logs-1624889476487.zip)

</details>

**Additional information**

- Android version: _7.0_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
Seems to be the same as #160
