### ISSUE TITLE
[Bug Report] Parent account login not working

### ISSUE THREAD

**Issue by Hamuni-forever** [SapuSeven/BetterUntis#189]
My first bug report, let's see what it gives :-)

I have a parents account for webuntis, logging in I cannot change to my son's data. Since I have no schedule /timetable (don't know the English word for Stundenplan) I cannot use this app. 
With the webuntis app I can see the Stundenplan. 
I would much prefer to use this app, so probably this helps. 
Thanks for the work, 
Alex 

<details>`
<summary>Logs</summary>

```
Anfragen-ID: 30
Fehlercode: -7001
Fehlermeldung: invalid element type: 15
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.android.packageinstaller_

**Comment by Lauritz-Tieste** [comment]
Maybe you can try it in the newest version?

**Comment by SapuSeven** [comment]
Parent login should be fixed in version 4.
Please reopen if you have any more issues.
