### ISSUE TITLE
[Feature Request] Messages of the day

### ISSUE THREAD

**Issue by mesarth** [SapuSeven/BetterUntis#19]
I don't know if you can access the "Messages of the day" via the API but for me it would be really useful to have access to these messages.

<details>
  <summary><i>Screenshots of Untis Mobile</i></summary>
  
![IMG_20191105_140413_681](https://user-images.githubusercontent.com/6097749/68210140-30999800-ffd5-11e9-8a6b-8d20f27136fe.jpg)
![IMG_20191105_140411_079](https://user-images.githubusercontent.com/6097749/68210147-32fbf200-ffd5-11e9-9170-cfef9965b50d.jpg)
</details>

**Comment by SapuSeven** [comment]
Yes, the API supports it.
It's already planned and will be implemented in the next release.

**Comment by SapuSeven** [comment]
I need some more test data, so I'll move the feature up a bit to release the new version earlier.

**Comment by SapuSeven** [comment]
OK, i created a [new branch](https://github.com/SapuSeven/BetterUntis/tree/motd) for this feature.
You can access the messages in the info center.

I couldn't find a school to test this with, so I'll only merge the branch to develop once I can confirm it works.

**Comment by mesarth** [comment]
> OK, i created a [new branch](https://github.com/SapuSeven/BetterUntis/tree/motd) for this feature.
> You can access the messages in the info center.
> 
> I couldn't find a school to test this with, so I'll only merge the branch to develop once I can confirm it works.

My school had a message up for today. As you can see in the screenshot below, the message is not displayed correctly. It needs some kind of HTML parsing.

![Screenshot_1576095733](https://user-images.githubusercontent.com/6097749/70657664-83addd00-1c5c-11ea-805d-6dab489fe53e.png)

**Comment by SapuSeven** [comment]
Right. Commit da183a87 should fix that. Try [build#185](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=185) and see if there are still any issues.

**Comment by mesarth** [comment]
Yep. That solved it.

**Comment by SapuSeven** [comment]
Great! Next release coming soon.
