### ISSUE TITLE
[Bug Report] App crash due to too many subjects at the same time

### ISSUE THREAD

**Issue by danielgoldbach68** [SapuSeven/BetterUntis#191]
**Description**

The app crashes when viewing a specific day (only occured, when viewing 1 day at a time, set in settings). The problem seems to occur when your class has too many lessons at the same time. 

While of course fixing that issue would be great, the actual problem is, that you can't filter subjects, or only show specific ones, as a timetable shown in the screenshot isn't helpful to anyone anyways. Here in Germany, where schools are barely digitalised, this issue is particularly wide spread, it makes WebUntis in general, no matter the app incredibly tedious to use.
This is already described in _[Feature Request] Better support for classes with multiple teachers_ #156 

My school doesn't support anonymous login, but I think I may give the credentials, as absolutely no confidential information is visible, due to very poor integration of Untis at our school.

<details>
  <summary><b>Screenshots</b></summary>

 
![Screenshot_20210913-151908](https://user-images.githubusercontent.com/52566328/133094700-77b47630-7f1e-40cf-8a9b-5eee7896d9be.png)
App shortly before the crash

![Screenshot_20210913-151855](https://user-images.githubusercontent.com/52566328/133094737-e8dcee30-a6d0-4a05-abe1-0849bc2d9b0b.png)
Error

![Screenshot_20210913-152518](https://user-images.githubusercontent.com/52566328/133094764-118cc710-3bd5-4246-aaaa-fe7aed9dd81f.png)
Same timetable in Untis mobile. (still not helpfull)
</details>

**Additional information**

 - Android version: Android 11
 - BetterUntis version: 3.4.5 (29)
 - Installation source: Google Play

**Comment by lm41** [comment]
The linked pull request adds the ability to filter subjects. Can you check [this artifact](https://output.circle-artifacts.com/output/job/08a476a0-209e-48f0-a9af-d6f8ee658537/artifacts/0/outputs/apk/debug/app-debug.apk) if this was helpful and drop suggestions in the linked pull request. 

You can access the filter in Settings -> Timetable -> Display Options -> Subjects to hide

**Comment by SapuSeven** [comment]
I'm assuming version 4 won't crash anymore as the items are rendered differently.
It would still be nice to have the ability to hide subjects, but this is addressed in #361
