### ISSUE TITLE
[Feature Request] Custom themes

### ISSUE THREAD

**Issue by wtquin** [SapuSeven/BetterUntis#193]
Make it possible to save your current settings to a theme. 

Then, allow people to switch between these themes/configs 

Also make it possible to apply the theme to different profiles, just like you can currently apply themes like "pixel" with one  click.

**Comment by SapuSeven** [comment]
I think the possibility to create multiple profiles (you can use the same account multiple times) already addresses this use case to a large extent.
As most users don't regularly add new profiles, a "settings preset" would be pretty complicated for what it does.
