### ISSUE TITLE
[Bug Report] Free Rooms

### ISSUE THREAD

**Issue by lm41** [SapuSeven/BetterUntis#199]
**Description**

If you use the Free Rooms feature and you have no right for this timetable, you gen an error.

<details>
  <summary><b>Logs</b></summary>
<br>
Anfragen-ID: 0 <br>
Fehlercode: -8509 <br>
Fehlermeldung: no right for timetable <br>
From the Logcat:
<code>2021-11-21 11:51:44.545 30424-30424/com.sapuseven.untis.debug D/TimetableLoaderDebug: target TimetableLoaderTarget(startDate=2021-11-15, endDate=2021-11-19, id=544, type=ROOM) (requestId 0): network request failed at Untis API level</code>
</details>

**Additional information**

 - Android version: 11
 - BetterUntis version: 3.4.5 and 3.4.5-DEBUG
 - Installation source: F-Droid / Own Build

**Comment by DreamyLynn** [comment]
This is intended. It is not possible to check whether the room is free if you don't have the rights to see it's timetable.

**Comment by lm41** [comment]
Yes, i know. One option is to disable the feature if you don't have the rights.
