### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by CPKreu** [SapuSeven/BetterUntis#202]
**Description**

I just opened the app and it just showed the crash screen for a second before immediately closing.

After re-opening it did the same thing.

It stopped immediately closing after I force stopped it and opened it again which presented me the crash screen and this stack trace:

![Screenshot_20211202-152453.png](https://user-images.githubusercontent.com/45312141/144441067-46a35c46-6013-4cb9-8b93-2389cd97fa02.png)

If I now press `Dismiss all` it shows my timetable for a second and repeats the same behavior as before.

I tried clearing cache and storage.

Cache didn't help at all while storage let me log in but after logging in it crashed again

**Additional information**

 - Android version: 12
 - BetterUntis version: 3.4.5
 - Installation source: Google Play

**Comment by SapuSeven** [comment]
Seems like Untis changed their API.
Thanks for reporting. This is being tracked in #201.
