### ISSUE TITLE
[Crash Report] 

### ISSUE THREAD

**Issue by x653** [SapuSeven/BetterUntis#203]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1638455958204.zip`
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
Missing info. I assume this is the same as #201.
