### ISSUE TITLE
[Feature Request] Display class services

### ISSUE THREAD

**Issue by Perflyst** [SapuSeven/BetterUntis#21]
In the Info section should be some menu to view class services like "Klassensprecher", "Tafeldienst" and "Ordnungsdienst"

**Comment by SapuSeven** [comment]
Is this data available in the original Untis mobile app?

**Comment by SapuSeven** [comment]
Closing this issue as I don't think the API supports these features. As long as the original Untis Mobile app doesn't access this data, I have no way of analyzing the API functions.
