### ISSUE TITLE
[Crash Report] App randomly crashing

### ISSUE THREAD

**Issue by Yumeo0** [SapuSeven/BetterUntis#212]
I don't know what happened yesterday but the App just started to crash on startup.

There are no log Files to be found anywhere on my Phone and I dont know how else to do it. If you need all the error codes I will try to screenshot all of them. Eventhough I think they are almost the same.

<details>
<summary>Screenshots</summary>

![Screenshot_20211203-072421](https://user-images.githubusercontent.com/60485613/144555833-d70a4f07-7c55-4b5e-b747-ba8780a85bfc.jpg)
![Screenshot_20211203-072623](https://user-images.githubusercontent.com/60485613/144555885-8f163fb6-41e0-48f8-a69c-263fdae9e758.jpg)
![Screenshot_20211203-072629](https://user-images.githubusercontent.com/60485613/144555909-08c6fbba-d4bf-4e87-aae5-e3fdae3be40d.jpg)
![Screenshot_20211203-072634](https://user-images.githubusercontent.com/60485613/144555930-a8c49677-b4ad-4ee0-8229-25274076b91c.jpg)
</details>

This is written on mobile so I'm sorry for typos or bad formatting.

- Android version: _11_
- BetterUntis version: _3.4.5 (29)_
- Installation source: Google Play Store

**Comment by Yumeo0** [comment]
The pictures didn't even load... I guess you can copy and open the links...

**Comment by SapuSeven** [comment]
Thanks for reporting. This is being tracked in #201.
