### ISSUE TITLE
[Crash Report] Crash at startup

### ISSUE THREAD

**Issue by bennetrr** [SapuSeven/BetterUntis#213]
**Description**
When I open BetterUntis, the app crashes instantly.

School ID: BK_Geldern
<details>
  <summary><b>Logs</b></summary>
  The app does not show me any error messages now.<br>
  The error messages I got a few hours ago was something like <code>The field 'message' could not be found</code>
</details>

**Additional information**

 - Android version: 8.1.0
 - BetterUntis version: 3.4.5
 - Installation source: Google Play

The original Untis App also crashed at startup, but a update I installed this morning fixed the issue.

**Comment by SapuSeven** [comment]
Thanks for reporting. This is being tracked in #201.
