### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by Persie0** [SapuSeven/BetterUntis#214]
<details>
<summary>Logs</summary>

```
Please attach the compressed log files to this issue.
They have been saved to `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1638790435383.zip`
```
</details>
Logs:
https://drive.google.com/file/d/1WY6Q4oRspFQcOr3sV0S79zalepTIdnn7/view?usp=drivesdk

**Additional information**

- Android version: _7.1.2_
- BetterUntis version: _3.4.5 (29)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Thanks for reporting. This is being tracked in #201.
