### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Gladox114** [SapuSeven/BetterUntis#220]
**Describe the solution you'd like**

BetterUntis's first screen is the "Personal Timetable" but I have no right for that timetable [Error: Request ID:9, Error code: -8509]
So I always go to classes and select my class to see my timetable.

My Feature suggestion is to save where I was last time. When Opening the app that the first screen will be my class because this was the last thing I opened.

I compiled the beta and would want to implement this feature myself but I have no clue where to look at in the code.

Maybe the Personal timetable error is a bug that also shouldn't happen... Or it works like it is intended but my school set up the users weirdly? (I have no clue about this topic)

**Comment by SapuSeven** [comment]
You can already set a custom personal timetable in Settings -> Timetable -> Custom Personal Timetable.

**Comment by Gladox114** [comment]
This feels awkward. I oversaw this feature. Maybe because it looked like text that you couldn't press on? Anyways this fixes my whole situation, thanks

**Comment by SapuSeven** [comment]
Glad this issue got resolved.
You're right, the message could be clearer, but I couldn't find a way to link straight to the relevant option.
