### ISSUE TITLE
[Bug Report] Lesson topic not loading

### ISSUE THREAD

**Issue by lm41** [SapuSeven/BetterUntis#221]
**Description**

_A clear and concise description of what the bug is.
Please add steps to reproduce the behavior._

_If your school supports anonymous login, you may also provide the school id for easier debugging._

The "Lehrstoff" doesn't load.

<details>
  <summary><b>Screenshots</b></summary>

![Screenshot_20211209-071048-702.png](https://user-images.githubusercontent.com/59062169/145343790-a57ad5df-1a1c-4147-83de-f72ff2dc24ee.png)

![Screenshot_20211209-071135-545.png](https://user-images.githubusercontent.com/59062169/145343801-d56a7350-df0a-44ac-b473-4fe53bf9e6f1.png)
  
_Add screenshots here to describe the problem.
  Please include screenshots of the original Untis Mobile app if applicable._
</details>

<details>
  <summary><b>Logs</b></summary>

  _Add a detailed stack trace / crash log here if applicable._
</details>

**Additional information**

 - Android version: Android 11
 - BetterUntis version: v3.4.5-DEBUG
 - Installation source: Github Issue (Bug occured in the versions before)

**Comment by Lauritz-Tieste** [comment]
Does this error still appear in BetterUntis 4?

**Comment by SapuSeven** [comment]
I will close this assuming it got fixed with version 4 due to inactivity.

**Comment by lm41** [comment]
I don't know if this was fixed, but it seems that my school is not giving this information to the students anymore.
