### ISSUE TITLE
[Bug Report] F-Droid build does not work

### ISSUE THREAD

**Issue by lm41** [SapuSeven/BetterUntis#225]
**Description**

_A clear and concise description of what the bug is.
Please add steps to reproduce the behavior._

The Java version of the F-Droid build system has to be changed. This can be changed in the yml file in the FdoidData repo like here: 

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9586

<details>
  <summary><b>Logs</b></summary>

   https://monitor.f-droid.org/builds/log/com.sapuseven.untis/30 

   `Traceback (most recent call last): File "/home/fbuild/fdroidserver/fdroidserver/build.py", line 1127, in main options.onserver, options.refresh): File "/home/fbuild/fdroidserver/fdroidserver/build.py", line 885, in trybuild build_server(app, build, vcs, build_dir, output_dir, log_dir, force) File "/home/fbuild/fdroidserver/fdroidserver/build.py", line 268, in build_server str(output, 'utf-8')) fdroidserver.exception.BuildException: Build.py failed on server for com.sapuseven.untis:3.4.6 ==== detail begin ==== == Installed Android Tools == 2021-12-09 18:19:51,716 DEBUG: Reading 'config.yml' 2021-12-09 18:19:51,727 INFO: Using /opt/android-sdk/build-tools/29.0.3/apksigner 2021-12-09 18:19:51,730 INFO: Creating log directory 2021-12-09 18:19:51,730 INFO: Creating temporary directory 2021-12-09 18:19:51,731 INFO: Creating output directory 2021-12-09 18:19:51,735 DEBUG: Getting git vcs interface for https://github.com/SapuSeven/BetterUntis 2021-12-09 18:19:51,735 DEBUG: > git --version git version 2.11.0 2021-12-09 18:19:51,950 INFO: Using git version 2.11.0 2021-12-09 18:19:51,951 DEBUG: Checking 3.4.6 2021-12-09 18:19:51,951 INFO: Building version 3.4.6 (30) of com.sapuseven.untis 2021-12-09 18:19:51,952 DEBUG: > sudo passwd --lock root passwd: password expiry information changed. 2021-12-09 18:19:52,171 DEBUG: > sudo SUDO_FORCE_REMOVE=yes dpkg --purge sudo (Reading database ... 64914 files and directories currently installed.) Removing sudo (1.8.19p1-2.1+deb9u3) ... Purging configuration files for sudo (1.8.19p1-2.1+deb9u3) ... Processing triggers for systemd (232-25+deb9u13) ... 2021-12-09 18:19:57,593 INFO: Getting source for revision e2f2cf573d20b385f4375295b3694c61030b9ce5 2021-12-09 18:19:57,594 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:57,594 DEBUG: > git rev-parse --show-toplevel 2021-12-09 18:19:57,806 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:57,806 DEBUG: > git submodule foreach --recursive git reset --hard 2021-12-09 18:19:57,910 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:57,910 DEBUG: > git reset --hard 2021-12-09 18:19:58,367 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:58,367 DEBUG: > git submodule foreach --recursive git clean -dffx 2021-12-09 18:19:58,477 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:58,477 DEBUG: > git clean -dffx 2021-12-09 18:19:58,587 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:58,588 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com fetch origin 2021-12-09 18:19:59,277 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:59,277 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com remote prune origin 2021-12-09 18:19:59,695 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:19:59,695 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com fetch --prune --tags --force origin 2021-12-09 18:20:00,109 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:20:00,109 DEBUG: > git remote set-head origin --auto 2021-12-09 18:20:00,529 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:20:00,530 DEBUG: > git checkout -f e2f2cf573d20b385f4375295b3694c61030b9ce5 2021-12-09 18:20:00,736 DEBUG: Directory: build/com.sapuseven.untis 2021-12-09 18:20:00,737 DEBUG: > git clean -dffx 2021-12-09 18:20:00,878 INFO: Creating local.properties file at build/com.sapuseven.untis/local.properties 2021-12-09 18:20:00,879 INFO: Creating local.properties file at build/com.sapuseven.untis/app/local.properties 2021-12-09 18:20:00,879 DEBUG: Removing debuggable flags from build/com.sapuseven.untis/app 2021-12-09 18:20:00,888 INFO: Cleaned build.gradle of keysigning configs at build/com.sapuseven.untis/app/build.gradle 2021-12-09 18:20:00,901 INFO: Cleaning Gradle project... 2021-12-09 18:20:00,901 DEBUG: Directory: build/com.sapuseven.untis/app 2021-12-09 18:20:00,901 DEBUG: > /home/vagrant/fdroidserver/gradlew-fdroid clean Found 7.0.2 via distributionUrl Running /opt/gradle/versions/7.0.2/bin/gradle clean Welcome to Gradle 7.0.2! Here are the highlights of this release: - File system watching enabled by default - Support for running with and building Java 16 projects - Native support for Apple Silicon processors - Dependency catalog feature preview For more details see https://docs.gradle.org/7.0.2/release-notes.html To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon. Daemon will be stopped at the end of the build FAILURE: Build failed with an exception. * Where: Build file '/home/vagrant/build/com.sapuseven.untis/app/build.gradle' line: 1 * What went wrong: A problem occurred evaluating project ':app'. > Failed to apply plugin 'com.android.internal.application'. > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8. You can try some of the following options: - changing the IDE settings. - changing the JAVA_HOME environment variable. - changing `org.gradle.java.home` in `gradle.properties`. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings BUILD FAILED in 32s 2021-12-09 18:20:34,634 ERROR: Could not build app com.sapuseven.untis: Error cleaning com.sapuseven.untis:3.4.6 ==== detail begin ==== Found 7.0.2 via distributionUrl Running /opt/gradle/versions/7.0.2/bin/gradle clean Welcome to Gradle 7.0.2! Here are the highlights of this release: - File system watching enabled by default - Support for running with and building Java 16 projects - Native support for Apple Silicon processors - Dependency catalog feature preview For more details see https://docs.gradle.org/7.0.2/release-notes.html To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon. Daemon will be stopped at the end of the build FAILURE: Build failed with an exception. * Where: Build file '/home/vagrant/build/com.sapuseven.untis/app/build.gradle' line: 1 * What went wrong: A problem occurred evaluating project ':app'. > Failed to apply plugin 'com.android.internal.application'. > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8. You can try some of the following options: - changing the IDE settings. - changing the JAVA_HOME environment variable. - changing `org.gradle.java.home` in `gradle.properties`. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings BUILD FAILED in 32s ==== detail end ==== 2021-12-09 18:20:34,635 DEBUG: Error encoutered, stopping by user request. ==== detail end ====`

</details>

**Comment by SapuSeven** [comment]
How would this work for new releases?
Do new releases automatically copy the `sudo` section from previous releases?

**Comment by lm41** [comment]
I guess so. From the F-Droid forum: https://forum.f-droid.org/t/build-log-for-failing-build/14676/5

**Comment by SapuSeven** [comment]
Great, thanks.
I'll submit a PR right away.

**Comment by SapuSeven** [comment]
Oh, apparently this has already been fixed:
https://gitlab.com/fdroid/fdroiddata/-/commit/60f234a40c52419397bb0bf45b29d61c9f9b9e39

**Comment by lm41** [comment]
Oh, nice!
