### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by johahauf** [SapuSeven/BetterUntis#227]
<details>
[logs-1639311026771.zip](https://github.com/SapuSeven/BetterUntis/files/7698684/logs-1639311026771.zip)

<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1639311026771.zip`

>

</details>


**Additional information**

- Android version: _10_
- BetterUntis version: _3.4.6 (30)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Thanks. This has already been addressed with v3.4.7 but google is having trouble reviewing the update so it could take a few more days for the update to show up.

**Comment by johahauf** [comment]
Used 3.4.4 (downloaded from github) and 3.4.7 (as beta tester from Google) and both show a crash when I am searching for the school. Unfortunately no crash log is created...

**Comment by lm41** [comment]
Have you tried to delete the app data?

**Comment by johahauf** [comment]
I deleted the complete App and installed it again. Do I need to do something in addition? At least my data seems to be lost, because the school data and login data is no longer available.

**Comment by lm41** [comment]
So you can't use the app right now?

**Comment by johahauf** [comment]
Yes, as soon as I type the school name it closes!

**Comment by lm41** [comment]
Ok, so it is not the same issue like in #229 Which version do you use? Still 3.4.6 or 3.4.7?

**Comment by johahauf** [comment]
Using 3.4.7 see #230 which I just created. After another fresh install I can reach that point.
