### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by nlnen** [SapuSeven/BetterUntis#229]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1639409837141.zip`
```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.android.packageinstaller_

**Comment by lm41** [comment]
Can you please delete the App data in the Android App settings? I guess I had the same Issue and this helped. You have to log in again and change back all settings but it works afterwards at least for me, so give it a try.

**Comment by nlnen** [comment]
Ok thanks, it worked now
