### ISSUE TITLE
"Failed to load timetable" even if notifications disabled

### ISSUE THREAD

**Issue by Perflyst** [SapuSeven/BetterUntis#23]
If the timetable cannot load in the morning because there is no internet connection I get a notification "Failed to load Timetable - You wont get any notification today" even if the notifications are disabled in the settings.

**Comment by SapuSeven** [comment]
Are you sure you disabled the preference? I cannot reproduce this issue and also didn't find any error in the program logic...

**Comment by Perflyst** [comment]
Yes it was disabled.
I did a clean install of BetaUntis and disabled again, will report back in the next few days

**Comment by SapuSeven** [comment]
Another thought: Did you create more than one profile at any point?

**Comment by SapuSeven** [comment]
Should be fixed it in the referenced commits.
