### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by HealingArcYT** [SapuSeven/BetterUntis#232]
# Logs
[logs-1639504482924.zip](https://github.com/SapuSeven/BetterUntis/files/7713767/logs-1639504482924.zip)

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Those crashes are from old versions. The version you are currently using has fixed these issues.
