### ISSUE TITLE
[Bug Report] Crash when placing widgets on Android 12

### ISSUE THREAD

**Issue by ghost** [SapuSeven/BetterUntis#238]
<details>
<summary>Logs</summary>

[logs-1640962303548.zip](https://github.com/SapuSeven/BetterUntis/files/7796463/logs-1640962303548.zip)

</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _fdroid_

**Comment by SapuSeven** [comment]
This doesn't look like a fatal issue to me. These warnings can be ignored.

**Comment by ghost** [comment]
I probably should've added that somewhere but if I remember correctly, this is the crash that happens when I try to place a widget on android 12. The crash can be ignored, as long as you don't use widgets. I liked using that widget.

**Comment by SapuSeven** [comment]
Should be fixed in v3.5.0
