### ISSUE TITLE
[Feature Request] Notification with room and lesson before the first lesson

### ISSUE THREAD

**Issue by SimonIT** [SapuSeven/BetterUntis#24]

**Comment by SapuSeven** [comment]
I added this feature in 37fca13b ([build#179](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=179)) but had no opportunity to test it yet.
It might or might not work correctly.

**Comment by SapuSeven** [comment]
I just tested it and it looks good to me.
It will be available in [release v3.2.0](https://github.com/SapuSeven/BetterUntis/milestone/3).
