### ISSUE TITLE
Mark supplemented lessons which are not a different subject as irregular?

### ISSUE THREAD

**Issue by DreamyLynn** [SapuSeven/BetterUntis#242]
I've noticed that supplemented lessons, where there is only a different teacher and not a different subject are not marked as irregular, making them hard to notice, especially when the teacher names are not displayed (when there is no space to display them). Should these lessons be marked as irregular?

**Comment by DreamyLynn** [comment]
In the official app they are marked as irregular.

**Comment by lm41** [comment]
Yes, a different color would be nice. Like purple in the original app.

**Comment by SapuSeven** [comment]
There's already some [`forceIrregular` logic in `MainActivity`](https://github.com/SapuSeven/BetterUntis/blob/13bc5000b914d2294dccbcb8c453a98d5b456766/app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt#L799-L807). You could take a look at that and figure out how to include the scenarios you mentioned. As far as I can see there's already a check if there's a teacher whose ID changed.

**Comment by SapuSeven** [comment]
I just noticed: Try to enable _Detect irregular lessons_ in the Timetable settings

**Comment by lm41** [comment]
That works, thank you!

**Comment by DreamyLynn** [comment]
I think this should be on by default

**Comment by lm41** [comment]
Yes, I would also prefer that

**Comment by SapuSeven** [comment]
Feel free to open a PR. This should be an easy change.

**Comment by SapuSeven** [comment]
Will be included in the Material 3 Update (#290)
