### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by ghost** [SapuSeven/BetterUntis#243]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1643105788146.zip`
```
</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.looker.droidify_

**Comment by SapuSeven** [comment]
Missing logs
