### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by avmase** [SapuSeven/BetterUntis#246]
Seltsamerweise taucht der Fehler nur bei betteruntis, aber nicht bei openuntis und untis_at auf. Auch vor dem letzten Update im Dezember gab es nur Fehler bei betteruntis. Schade, denn im Alltag ist betteruntis unschlagbar.

<details>
<summary>Logs</summary>

```
Anfragen-ID: 4
Fehlercode: 3
Fehlermeldung: o7.b: Field 'staffInfo' is required for type with serial name 'com.sapuseven.untis.models.untis.timetable.PeriodText', but it was missing
```
</details>

**Additional information**

- Android version: _8.0.0_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
Dieser Fehler wurde in Version 3.4.8 behoben.
Es tut mir leid, dass du in letzter Zeit so viele Probleme mit BetterUntis hattest. Grund dafür ist, dass wir uns an die originale Untis App anpassen müssen und somit auf Änderungen der Untis-Schnittstelle nur spät reagieren können.

**Comment by avmase** [comment]
Openuntis wurde seit fast 3 Jahren nicht aktualisiert. Trotzdem war es nicht vom Dezember- und Januar-Fehler betroffen. Wie kann das sein? Ich würde das gerne verstehen.



Am 31. Januar 2022 10:02:02 MEZ schrieb SapuSeven ***@***.***>:

**Comment by SapuSeven** [comment]
Der Unterschied liegt in der Verarbeitung der API-Daten.
OpenUntis verwendet keine Datenmodelle, das heißt die Daten werden "on-demand" aus dem Ergebnis abgefragt.
BetterUntis hat für jeden Datentyp der API ein entsprechendes Modell im Code. Dieses Modell vereinfacht den Umgang mit den Daten im Code, muss jedoch stets aktuell sein, ansonsten kommt es zu Abstürzen.
