### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by RedCommander735** [SapuSeven/BetterUntis#247]
**Description**

If I try to refresh the timetable it shows an error code and doesn't refresh. 

<details>
  <summary><b>Screenshots</b></summary>
![Screenshot_20220128-123003.jpg](https://user-images.githubusercontent.com/40245965/151539943-f6779183-7d5a-4072-9628-0411c3442a76.jpg)
</details>

<details>
  <summary><b>Logs</b></summary>
App crashes if I try to open logs. 
</details>

**Additional information**

 - Android version: 8.0.0
 - BetterUntis version: 3.4.7
 - Installation source: Google Play

**Comment by SapuSeven** [comment]
This has been fixed in version 3.4.8. You can opt-in as a beta tester on Google Play to receive the update sooner.
