### ISSUE TITLE
Phone gets unmuted during lessons

### ISSUE THREAD

**Issue by SimonIT** [SapuSeven/BetterUntis#25]
The reason is probably that we got double lessons at our school. The first lessons is from 08:10 to 08:55 and the second one is from 08:55 to 09:40. I think the problem is that BetterUntis tries to unmute and mute the phone at the same time 08:55. This can result in a muted or unmuted phone because of inaccuracy of the timed broadcast. A simple solution is to check whether a difference between an end and a begin of a lesson is.

**Comment by SapuSeven** [comment]
Thanks for reporting, I'll look into it

**Comment by SapuSeven** [comment]
Should be fixed with 9376c053.
I haven't tested it though as my school has no lessons without breaks.

**Comment by SimonIT** [comment]
The fix isn't currently in the play store, right?

**Comment by SapuSeven** [comment]
Not yet, you'll have to wait for the next release
