### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by HealingArcYT** [SapuSeven/BetterUntis#251]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 6
Fehlercode: 3
Fehlermeldung: o7.b: Field 'staffInfo' is required for type with serial name 'com.sapuseven.untis.models.untis.timetable.PeriodText', but it was missing
```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
This is fixed with version 3.4.8. You can opt-in as a beta tester to receive the update sooner.
