### ISSUE TITLE
[Discussion] Alternative error reporting

### ISSUE THREAD

**Issue by SapuSeven** [SapuSeven/BetterUntis#253]
As there are many issues being opened for crashes without any useful information, I'd like to explore some different options of in-app error reporting.

Right now, the app provides a "Report" button, which redirects the user to GitHub where they can create a new issue.

The problem is that many users do not regularly use GitHub and thus are unfamiliar with the process. This leads to a large number of reports without the required logs etc.

In this issue I'd like to collect suggestions for an alternative error/crash reporting mechanism which is not necessarily linked to GitHub and automatically collects all necessary information without user input.

**Comment by DreamyLynn** [comment]
We might be able to apply for a free open-source project sentry plan (https://sentry.io/for/open-source/). As Sentry itself is pretty popular and open-source I think it could be a good fit for BetterUntis.

**Comment by nebton525** [comment]
FYI the latest debug build from your website works fine

**Comment by SapuSeven** [comment]
Update: The request for an open source license at Sentry got approved!
@DreamyLynn if you want you can write me your e-mail-address in a PM and I'll add you to the organization.

**Comment by SapuSeven** [comment]
Work on implementing Sentry is being done in the `sentry` branch.
