### ISSUE TITLE
[Crash Report] starts slowly and crashes

### ISSUE THREAD

**Issue by goldos24** [SapuSeven/BetterUntis#265]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1644941936399.zip`
```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.8 (32)_
- Installation source: _org.fdroid.fdroid.privileged_

**Comment by DreamyLynn** [comment]
The logs are missing. please add them.
