### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by derjoshder** [SapuSeven/BetterUntis#266]
[logs-1645527372986.zip](https://github.com/SapuSeven/BetterUntis/files/8116082/logs-1645527372986.zip)
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1645527372986.zip`
```
</details>

**Additional information**

- Android version: _9_
- BetterUntis version: _3.4.8 (32)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
First, please try the latest version (3.5.1).
If the error still happens, please provide detailed steps to reproduce.
