### ISSUE TITLE
[Bug Report] German Localisation string not fully readable

### ISSUE THREAD

**Issue by Lamdarer** [SapuSeven/BetterUntis#267]
### Steps to Reproduce

1. Android is set to Deutsch (Deutschland)
2. Open BetterUntis
3. Open the hamburger menu on the left
4. Click on the currently selected profile to see the option for adding new profiles
5. The hint that you can edit profiles by long-pressing them is not fully readable.

### Expected Result

The English localization says "Long-press a profile to edit", so the whole string is readable
![BetterUntis_localisation2](https://user-images.githubusercontent.com/50927784/155885917-148ec11f-f1d4-4431-a311-4666d2b454bb.jpeg)

### Actual Result

The german localization is cut of
![BetterUntis_localisation1](https://user-images.githubusercontent.com/50927784/155885954-63e473e6-0067-4372-82e7-1ef58a564d67.jpeg)
f

### Android Version

Android 10

### BetterUntis Version

3.4.8 (32)

### Installation Source

F-Droid

**Comment by SapuSeven** [comment]
Should be resolved with the Material 3 Update (#290)
