### ISSUE TITLE
Matrix room doesn't work

### ISSUE THREAD

**Issue by 3nt3** [SapuSeven/BetterUntis#268]
**Steps to reproduce**
Open the matrix room linked in readme `#github:sapuseven.com` in any matrix client (tried [cinny](https://cinny.in) and fluffychat)

**Expected Result**
A working chatroom

**Actual result**
Room not found

**Comment by lm41** [comment]
There is another room which is working: https://matrix.to/#/#SapuSeven_BetterUntis:gitter.im

**Comment by SapuSeven** [comment]
Sorry, I messed that one up.
I don't actively use Gitter anymore so I suggest joining the room using the correct tag: `#github-betteruntis:sapuseven.com`.
I'll also edit the README file right away.

**Comment by Lamdarer** [comment]
> Sorry, I messed that one up. I don't actively use Gitter anymore so I suggest joining the room using the correct tag: `#github-betteruntis:sapuseven.com`. I'll also edit the README file right away.

@SapuSeven did anything change? I cant join the matrix room because apparently I do not belong to "any of the required rooms/spaces to join this room" as the Element error message says.
The Gitter room works fine however, but as you said you don't check it it probably doesn't matter.

**Comment by SapuSeven** [comment]
I just updated the room preferences. Can you try again please?

**Comment by Lamdarer** [comment]
Works now, thx.
