### ISSUE TITLE
[Feature Request] Translation

### ISSUE THREAD

**Issue by nautilusx** [SapuSeven/BetterUntis#27]
Could you use weblate.org for the translation?

It is free (gratis) for Free Software projects, uses the GPLv3 and is easier to contribute for translators.

**Comment by SapuSeven** [comment]
Sounds like a good idea. I'll look into this service.

**Comment by Perflyst** [comment]
In which countries is Untis used?

**Comment by SapuSeven** [comment]
Looking at the [Untis website](https://www.untis.at/), they are available worldwide in 35+ languages.
Currently the Google Play version of BetterUntis is only used in Austria and Germany.

**Comment by SapuSeven** [comment]
Translations updated in 1c673890. Available in the next release.

**Comment by SapuSeven** [comment]
As Weblate still hasn't responded to my Open Source License request, I decided to try Crowdin to translate BetterUntis.

You can contribute here:
https://crowdin.com/project/betteruntis/invite?d=m645j4g6b5c543331763b393u4b3l4

**Comment by nautilusx** [comment]
Thank you.

I'll ask the dev of weblate. Maybe I see him the next days.
Weblate is much better - userfriendly and privacyfriendly.

**Comment by nautilusx** [comment]
@SapuSeven: Did you get an answer from weblate?

**Comment by SapuSeven** [comment]
No, I didn't receive anything

**Comment by nautilusx** [comment]
I received the answer on 30.12.2019 that the hosting is possible. It takes a while because they do it only once a month.
You did the request on https://hosted.weblate.org/hosting/, right?

**Comment by SapuSeven** [comment]
I did, but also didn't get any message if I remember correctly

**Comment by nautilusx** [comment]
Okay, just give me a hint if you don't get anything by the end of the month.

**Comment by SapuSeven** [comment]
Thanks, I just checked and noticed I did receive a confirmation for my hosting request on 3. Dec 2019.

Just to be sure, I signed up again, maybe my previous request somehow got lost.

**Comment by nautilusx** [comment]
I am very excited to be able to do the translations on weblate.org soon.
