### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by goldos24** [SapuSeven/BetterUntis#276]
[logs-1651467548985.zip](https://github.com/SapuSeven/BetterUntis/files/8600867/logs-1651467548985.zip)
#<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1651467548985.zip`
```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.4.8 (32)_
- Installation source: _org.fdroid.fdroid.privileged_

**Comment by SapuSeven** [comment]
First, please try the latest version (3.5.1).
If the error still happens, please provide detailed steps to reproduce.
