### ISSUE TITLE
Messenger not opening correctly

### ISSUE THREAD

**Issue by RedCommander735** [SapuSeven/BetterUntis#279]
### Steps to Reproduce

open App  --> open Menu  --> Tap on "Messenger" button

### Expected Result

The Untis Messenger App should open up

### Actual Result

The Play Store opens up on the page for the Untis Messenger even though it is already installed.

### Android Version

Android 11

### BetterUntis Version

3.5.0 (33)

### Installation Source

Google Play

**Comment by SapuSeven** [comment]
@Domi04151309

**Comment by Domi04151309** [comment]
This is because of the new query restrictions in Android 11. You have to add the package name in the manifest for it to work. See https://github.com/Domi04151309/HomeApp/blob/9aa51db0547a32a95d83a6371299c6d9b37aefe5/app/src/main/AndroidManifest.xml#L19
