### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by florian-sabonchi** [SapuSeven/BetterUntis#281]
Maybe we should only show the course a student is in (see Thursday afternoon).

![Screenshot_20220514-225416](https://user-images.githubusercontent.com/54689374/168447839-4fdee7b0-a297-4dff-bbe0-22b0ebc84f03.png)

**Comment by SapuSeven** [comment]
Correct me if I'm wrong, but I think its impossible for BetterUntis to determine which courses you are in without the Untis API providing the required information.

**Comment by qwerty287** [comment]
You could let the users select which courses they are in (also see https://github.com/SapuSeven/BetterUntis/issues/102) and then hide everything else.

**Comment by SapuSeven** [comment]
I see. Closing this as a duplicate, future changes will be tracked in #102.
