### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by florian-sabonchi** [SapuSeven/BetterUntis#282]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 13
Fehlercode: 2
Fehlermeldung: unexpected end of stream on com.android.okhttp.Address@93edf9a3
```
</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.5.0 (33)_
- Installation source: _com.android.packageinstaller_

**Comment by SapuSeven** [comment]
Looks like a network error.
I'll close this issue as a one-off.
If this happens more often, please feel free to open it again.
