### ISSUE TITLE
[Bug Report] Do-Not-Disturb turns off during lessons

### ISSUE THREAD

**Issue by bennetrr** [SapuSeven/BetterUntis#283]
### Steps to Reproduce

1. Enable the Automatic Do-Not-Disturb feature
2. Wait

### Expected Result

The Do-Not-Disturb mode of Android should turn on when the lesson begins and turn off when the lesson ends.

### Actual Result

The Do-Not-Disturb mode of Android turns on at the beginning of the lesson and turns off in the middle of the lesson.

### Android Version

8.1.0

### BetterUntis Version

3.5.0 (33)

### Installation Source

Google Play

### Additional information

It is possible, that the Do-Not-Disturb mode turns off when a notification from the Untis Messenger comes in. I think, that all moments, when my smartphone notified my loudly in class, it was the Untis Messenger.

**Comment by lm41** [comment]
For me it doesn't work at all (see #275). I don't know if it is an android 12 related issue in my case.

**Comment by SapuSeven** [comment]
I will move this discussion to #275, as this seems to be related.
