### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Moosbee** [SapuSeven/BetterUntis#285]
<details>
Unknown JSON object "blockHash" encountered
<summary>Logs</summary>

```
Unknown JSON object "blockHash" encountered, value: 2119308709

```

- Android version: _10_
- BetterUntis version: _3.5.0 (33)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Thanks for reporting.
This is a non-critical error, so unless you experienced any other issues, I'll see this as resolved.
