### ISSUE TITLE
[Feature Request] Demo Mode

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#289]
### Problem Statement

I assume that the current contributors do not have access to an Untis Backend System because they no longer go to school.

### Solution Ideas

Some kind of demo mode would be a nice way to continue testing new features and development, and also for users to get familiar with the possibilities of the app. Maybe this could be done by adding a kind of proxy class for requests that can be set to demo mode for offline access. Alternatively a simulated backend hosted somewhere would be possible too.

Priority: low; not a main focus

**Comment by Domi04151309** [comment]
This would be something like the [Testing-API](https://github.com/SapuSeven/BetterUntis/wiki/Testing-API).

**Comment by SapuSeven** [comment]
Implemented with 6e7b48e and part of the Material 3 Update (#290)
