### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Xeniamesser** [SapuSeven/BetterUntis#291]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 4
Fehlercode: -8509
Fehlermeldung: no right for timetable
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.5.0 (33)_
- Installation source: _com.android.vending_

**Comment by Xeniamesser** [comment]
Hey

**Comment by Xeniamesser** [comment]
He

**Comment by SapuSeven** [comment]
Not a bug.
You don't have the rights to view the timetable you selected.
Please stop spamming.
