### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by julianx03** [SapuSeven/BetterUntis#294]
<details>
<summary>Logs</summary>

```
Request ID: 3
Error code: 3
Error message: u7.h: Unexpected JSON token at offset 293: Expected start of the array '[', but had ':' instead
JSON input: ....."excuseStatuses":[],"holidays":null,"klassen":[{"id":2829,"n.....
```
</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.5.0 (33)_
- Installation source: _com.android.vending_

**Comment by new-on-github** [comment]
Same problem here. Even after deleting all data...

Maybe someone has a idea for a solution. This would be really nice.

By the way: Thanks a lot for this app.

**Comment by SapuSeven** [comment]
Thanks for the report. I'll publish a hotfix to address this soon

**Comment by new-on-github** [comment]
> Thanks for the report. I'll publish a hotfix to address this soon

This would be amazing. Thanks a lot!

**Comment by SapuSeven** [comment]
https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=896
Can you please check out this debug build and verify it works?
I can issue a release once it's confirmed working.

**Comment by julianx03** [comment]
Yes it is working! Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SapuSeven** [comment]
Glad to hear! PlayStore Update for version 3.5.1 is on the way.

**Comment by new-on-github** [comment]
Is the fdroid version also on the way?

Thanks a lot for your work.

**Comment by SapuSeven** [comment]
Yes, FDroid releases are synced automatically.
