### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by ogsadmin** [SapuSeven/BetterUntis#297]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 2
Fehlercode: -7001
Fehlermeldung: invalid element type: 12
```
</details>

**Additional information**

- Android version: _13_
- BetterUntis version: _3.5.0-DEBUG (33)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
First, please try the latest version (3.5.1).
If the error still happens, please provide detailed steps to reproduce.

**Comment by ogsadmin** [comment]
Thanks! It is working perfectly with V3.5.1. 

As a side note: There also might have been some issues on the server side/API. They asked all users to report problems with the web frontend, so obviously either server software or server configuration had some problems... 

Thanks again and keep up the great work - in my opinion your app is way better than the "official" one :-)
