### ISSUE TITLE
Different color if the room has been changed

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#299]
### Problem Statement

A feature that shows a different color if the room has been changed is useful. Please add the new color in the customization menu.

**Comment by SapuSeven** [comment]
This should be covered under "Irregular Lesson".
Did you check out the option "Timetable -> Detect irregular lessons"?

**Comment by Lauritz-Tieste** [comment]
This option ist existing! It is working! Thanks!

**Comment by SapuSeven** [comment]
Great to hear!
See #242 - the setting will be enabled by default in a future release.
