### ISSUE TITLE
Date obstructs timetable

### ISSUE THREAD

**Issue by Jan200101** [SapuSeven/BetterUntis#3]
Testing out the latest revision of the develop branch as of writing yielded this
![IMG_20190921_190732](https://user-images.githubusercontent.com/15076013/65376685-2c265380-dca3-11e9-9505-1d8556bf4381.jpg)

**Comment by SapuSeven** [comment]
This looks like a free day where elements are still sent for that day.

Could you show me the same timetable in the original Untis app? I'd like to see how they handled this issue.

**Comment by Jan200101** [comment]
![IMG_20190921_192503](https://user-images.githubusercontent.com/15076013/65376898-03538d80-dca6-11e9-97d5-51e7a6bd1717.jpg)
I also have an example of an actual free day
![Screenshot_2019-09-21-19-25-06-476_com grupet web app](https://user-images.githubusercontent.com/15076013/65376900-0d758c00-dca6-11e9-8460-05921e60afcb.jpg)
and a free day with elements
![image](https://user-images.githubusercontent.com/15076013/65376916-2d0cb480-dca6-11e9-96b2-e0ea9ac8db9b.png)

**Comment by SapuSeven** [comment]
Thanks, I decided to draw holidays only if the day contains no elements. Could you test the app again with the latest commit?

**Comment by Jan200101** [comment]
works as described
