### ISSUE TITLE
[Feature Request] Add button to Appbar, which shows today

### ISSUE THREAD

**Issue by connectety** [SapuSeven/BetterUntis#30]
Please add a button to the top right of the screen (in the AppBar, on the personal timetable), which when clicked scrolls to today.
The button should show a calender icon. Maybe also show the current date in it.

I know you can click on the calendar icon and than click on today. But we got free screenspace there and it adds a neat shortcut.

I got this idea from the Orignal Untis app.

**Comment by SapuSeven** [comment]
It's a nice idea but I don't want to straight up copy the original app too much.
You can already long-press the date selection button in the top left corner to quickly jump to today.

**Comment by connectety** [comment]
Oh, I didn't know about the long press shortcut.
Thanks for the quick answer and the nice app.
And sorry for your inconvenience.

**Comment by SapuSeven** [comment]
No worries, thanks for your feedback :)
