### ISSUE TITLE
Replace null with unknown in irregular lessons

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#300]
### Problem Statement

In the case of a Schol lesson in which the teacher is represented by unknown, null is displayed. Could you write something like unknown?

![Screenshot_20220914-070909_BetterUntis](https://user-images.githubusercontent.com/84938977/190066574-2368192a-7209-4992-98a1-0ec1a768efd1.jpg)

**Comment by SapuSeven** [comment]
Thanks, will fix this in the Material 3 update.

**Comment by SapuSeven** [comment]
Fixed with 3fd232d2e12d1347c14219926612673da0ccefea
