### ISSUE TITLE
[Feature Request] Designing (Connectivity icon)

### ISSUE THREAD

**Issue by Cameo007** [SapuSeven/BetterUntis#302]
### Problem Statement

I would suggest one of the following icons for the Connectivity setting:
- https://fonts.google.com/icons?selected=Material+Symbols+Outlined:sync:FILL@0;wght@400;GRAD@0;opsz@48
- https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Arefresh%3A

![sync](https://user-images.githubusercontent.com/80521473/190436348-562095cb-9d33-49d6-871d-513d136693e6.png)
![refresh](https://user-images.githubusercontent.com/80521473/190436361-60ac17d7-2f69-46bd-8b76-4e16065922d6.png)

**Comment by SapuSeven** [comment]
I'd prefer the first one.
Another idea:
![web](https://user-images.githubusercontent.com/9549504/190932048-7a34f9ec-8991-472d-a47b-bdb7723aaf13.png)
(vote :+1:/:-1: )
