### ISSUE TITLE
[Feature Request] Canceled hours crossed out

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#305]
### Problem Statement

It would be good if the canceled hours were crossed out on the timetable in the BetterUntis app. (As in the original Untis Mobile App)

**Comment by SapuSeven** [comment]
I originally decided against that for the following reasons:
- It would be extra effort for the week view implementation to change the item rendering
- I thought it doesn't really fit the overall design
- If you want a strong indication of cancelled lessons, you can drastically change the background color or hide the items altogether.

**Comment by Lauritz-Tieste** [comment]
understood.  I understand your point of view
