### ISSUE TITLE
[Bug Report] Long click in nav not working when opened by swipe

### ISSUE THREAD

**Issue by DrMaxNix** [SapuSeven/BetterUntis#306]
### Steps to Reproduce

1. open the app (you should see your personal timetable)
2. open the drawer menu by pressing the hamburger icon
3. try to delete a timetable by long-clicking on its name
4. close and restart the app
5. open the drawer menu by swiping from left to right with your finger
6. try to delete a timetable by long-clicking on its name

### Expected Result

In both cases the confirmation dialog should show up

### Actual Result

The dialog only shows up when the drawer menu was opened using the button but not using a swipe
After having opened the drawer menu using the button once, it always works

### Android Version

Android 12 (Calyx OS)

### BetterUntis Version

3.5.1 (34)

### Installation Source

F-Droid

**Comment by SapuSeven** [comment]
Thanks, can confirm.
This will be fixed with the Material 3 update (#290).
