### ISSUE TITLE
[Bug Report] IDs of classes are not shown in teacher's timetable

### ISSUE THREAD

**Issue by Ser-Bronn** [SapuSeven/BetterUntis#307]
### Steps to Reproduce

Login as a teacher and open timetable

### Expected Result

IDs of classes should be shown in teacher's timetable.

### Actual Result

Question marks instead of class IDs
![screenshot2](https://user-images.githubusercontent.com/113766626/190851003-1d0bb9e7-aacb-4549-9d2a-7cf10147480a.png)

### Android Version

Android 12

### BetterUntis Version

3.5.1

### Installation Source

F-Droid

**Comment by SapuSeven** [comment]
That's weird.
Please try to refresh the profile data manually:
1. open the drawer
2. tap on the profile name at the top
3. long-press the profile in the list below
4. tap on 'login'

**Comment by Ser-Bronn** [comment]
Great! That works!
Thank you so much! for your great work!
