### ISSUE TITLE
[Bug Report] No rights for timetable

### ISSUE THREAD

**Issue by KaratekHD** [SapuSeven/BetterUntis#31]
**Description**
The app shows an error message saying "No right for timetable".

**Actual behavior**
Sign in and try to show the timetable

**Expected behavior**
The timetable is correctly shown.

<details>
  <summary><b>Screenshots</b></summary>

![Screenshot_20191215-115923_BetterUntis](https://user-images.githubusercontent.com/38097062/70861801-71b98c00-1f33-11ea-95de-0d0206621506.png)

![Screenshot_20191215-115929_BetterUntis](https://user-images.githubusercontent.com/38097062/70861804-7716d680-1f33-11ea-8510-d838f86f3e96.png)

</details>

<details>
<summary><b>Crash Log</b></summary>

```
Request ID: 6
Error code: -8509
Error message: no right for timetable
```
</details>

**Additional information (please replace)**
 - Android 9
 - BetterUntis version 3.1.1 (15) [Appears in latest debug build as well]

**Comment by Perflyst** [comment]
Are you allowed to access this class in webuntis? I am also not allowed to access specific rooms and get this error.

**Comment by KaratekHD** [comment]
Yes I am:
![image](https://user-images.githubusercontent.com/38097062/70862158-efcc6180-1f38-11ea-86ec-d38f15d7f68a.png)

**Comment by SapuSeven** [comment]
I'm sorry, but it doesn't look like I can do anything about that.
Are you sure you are logged in with the same account also selected the correct class in BetterUntis?

**Comment by SapuSeven** [comment]
Closing as not reproducible and inactive.

**Comment by iw0nderhow** [comment]
Sorry for digging up old issues - I just encountered this too. 
My school provides me with a shared account for the whole class, which does not have a "personal timetable" as it seems -- it only has access to the timetable of my class via the class selection. WebUntis and Untis Mobile seem to have a way to detect this, and automatically show the timetable of the class (which is the only one the account can access.) BetterUntis and OpenUntis currently don't detect this, and so fail except when the timetable for the class is explicitly selected.

**Comment by SapuSeven** [comment]
Oh, that certainly makes sense. Without a test account to work with I will probably not be able to fix this.

As a workaround, you can change the personal timetable in the settings menu.

**Comment by iw0nderhow** [comment]
If it helps, I can provide a dump of the communication between WebUntis and the server.

**Comment by SapuSeven** [comment]
That would be very helpful.
Please include the full login process from Untis Mobile and BetterUntis.
You can send it to me at betteruntis@sapuseven.com

**Comment by MoonPadUSer** [comment]
Ehm, I just encountered this too. Unless there is already a workaround I maybe can take a look at it myself, that way I'd have an account to test stuff on
