### ISSUE TITLE
[Bug Report] page switched after orientation change

### ISSUE THREAD

**Issue by KaktusXY** [SapuSeven/BetterUntis#314]
### Steps to Reproduce

Switch to any page except the current one (e.g. next week) and rotate your device

### Expected Result

staying on page

### Actual Result

switched back to current page/week

### Android Version

Android 11

### BetterUntis Version

3.5.1 (34)

### Installation Source

F-Droid

**Comment by SapuSeven** [comment]
This will be fixed with the Material 3 Update (#290)
