### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Lostjohnnx** [SapuSeven/BetterUntis#315]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 5
Fehlercode: -8509
Fehlermeldung: no right for timetable
```
</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.vending_

**Comment by Lauritz-Tieste** [comment]
The error says you don't have the rights to view the requested timetable.  This occurs, for example, when a student wants to view the teacher substitution plan
