### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by 37gitts** [SapuSeven/BetterUntis#317]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1665115703517.zip`
```
</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.google.android.packageinstaller_

**Comment by SapuSeven** [comment]
Missing the log files here. Please reopen the issue if you upload the files.
