### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by Bikholf** [SapuSeven/BetterUntis#318]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1665413615912.zip`
```
</details>

**Additional information**

- Android version: _13_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Missing the log files here. Please reopen the issue if you upload the files.
