### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by auroraanna** [SapuSeven/BetterUntis#323]
<details>
<summary>Logs</summary>

```
Unknown JSON object "blockHash" encountered, value: 929909106

```
</details>

**Additional information**

- Android version: _11_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Thanks, will keep this in mind, but this shouldn't cause any issues within the app.
If you get too much error messages, try to disable "Enable additional error messages" in general settings.
