### ISSUE TITLE
[Feature Request] Notifications before first lesson ICON

### ISSUE THREAD

**Issue by W113565456** [SapuSeven/BetterUntis#324]
### Problem Statement

My Icon proposal
![c21063f4-91d8-4e03-b951-afc86f3da798](https://user-images.githubusercontent.com/108750896/203573132-31125a67-f9d9-4f55-ad42-5d7c9a952866.png)

**Comment by SapuSeven** [comment]
Thanks for your input, but please have a look at [the guidelines for designing material icons](https://m3.material.io/styles/icons/designing-icons).
The icon style should be consistent across the app, which is definitely not the case for this icon.
