### ISSUE TITLE
[Feature Request] Preventing the password from being displayed (after the account has been created)

### ISSUE THREAD

**Issue by sedding** [SapuSeven/BetterUntis#327]
### Problem Statement

In the settings of a profile (long click on an existing profile > "Edit profile") you can make the user password visible - simply by clicking on the eye icon.

This is a problem for our intended use: We want to use BetterUntis on a touchscreen publicly accessible to students, with a "dummy user" who is allowed to view the timetables of all classes

### Solution Ideas

It should be prevented that the password can be made readable in the "Edit profile" dialogue of an existing profile
Of course, the password-field can (should) still be editable. It would be sufficient if the eye icon were not displayed.

**Comment by SapuSeven** [comment]
That makes sense. I'll add it to the Material 3 update TODO (#290).

**Comment by SapuSeven** [comment]
Done, will be included in the next update :+1:
