### ISSUE TITLE
Limit the number of blocks that can be seen horizontally

### ISSUE THREAD

**Issue by MatsG23** [SapuSeven/BetterUntis#331]
### Problem Statement

There is no limit how many blocks BetterUntis shows horizontally in the WeekView. If there are too many blocks in one box, you can only see stripes and not click on it anymore.

### Solution Ideas

If there are too many blocks in one WeekView, only show three blocks and show the others in a tab view if you clicked on the block.

By "block" I mean the combination of a day and one time frame in the WeekView.

**Comment by lm41** [comment]
![image](https://user-images.githubusercontent.com/59062169/204607112-1490ce3c-8778-4fb9-8f41-ea65dee63bc1.png)
Are you talking about this?

**Comment by MatsG23** [comment]
Yes, sometimes there are many blocks in one time frame.
It should be limited how many blocks can be horizontally displayed in one time frame (please show some icon when hiding other subjects).

**Comment by Lauritz-Tieste** [comment]
I think that has a lot to do with #156

**Comment by lm41** [comment]
Closed as duplicate of #156
