### ISSUE TITLE
[Bug Report] some texts are not translated

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#334]
### Steps to Reproduce

1. Open the App 
2. Open the navigation drawer

### Expected Result

Actually, the texts marked on the screenshot should be translated into German.
![Screenshot_20221130-142006_BetterUntis~2](https://user-images.githubusercontent.com/84938977/204807586-a40c474d-adc8-41bd-a731-bb5411b6e272.jpg)

### Actual Result

Some texts are not translated

### Android Version

Android 12

### BetterUntis Version

3.5.1 Material 3 Design Alpha

**Comment by Lauritz-Tieste** [comment]
I have checked most of the menus and I have found some more untranslated messages: 

![Screenshot_20230127_140604_BetterUntis~2.jpg](https://user-images.githubusercontent.com/84938977/215094894-2eb2655f-df6c-4833-9c71-3518d11c9007.jpg)

![Screenshot_20230127_140617_BetterUntis~2.jpg](https://user-images.githubusercontent.com/84938977/215094907-d396e055-671e-4a69-a589-ab4f48fcc5b0.jpg)

![Screenshot_20230127_140648_BetterUntis~2.jpg](https://user-images.githubusercontent.com/84938977/215094916-8b7a8186-8ce8-4966-aa47-e9654486c575.jpg)

**Comment by SapuSeven** [comment]
Thanks, will be fixed shortly.

**Comment by Lauritz-Tieste** [comment]
Pleased fix this little Bug: 
![Screenshot_20230128_162602_BetterUntis.jpg](https://user-images.githubusercontent.com/84938977/215274914-d73cf402-5f79-4e5c-92e9-ad898500fd53.jpg)

**Comment by Lauritz-Tieste** [comment]
Remember to Change this text
![Screenshot_20230128_163133_BetterUntis.jpg](https://user-images.githubusercontent.com/84938977/215275702-a80064df-e6bf-471b-ad39-b1f368f1a08d.jpg)

**Comment by SapuSeven** [comment]
Done, fa6943ae54105f6775a81316642dbb0279df7b2d

**Comment by SapuSeven** [comment]
> Remember to Change this text ![Screenshot_20230128_163133_BetterUntis.jpg](https://user-images.githubusercontent.com/84938977/215275702-a80064df-e6bf-471b-ad39-b1f368f1a08d.jpg)

I won't bother with these settings, they will be removed/replaced by Sentry later.

**Comment by Lauritz-Tieste** [comment]
![Screenshot_20230130_153255_BetterUntis.jpg](https://user-images.githubusercontent.com/84938977/215505733-97aed3f5-88a3-4850-a384-6a62954f3bc0.jpg)

Please translate the "general" text.

**Comment by Lauritz-Tieste** [comment]
![Screenshot_20230214_221524_BetaUntis.jpg](https://user-images.githubusercontent.com/84938977/218865985-1daaeae9-a4ef-4f6e-ba2b-1897d230618f.jpg)

Please translate "from" and "to" as well as the comment before

**Comment by SapuSeven** [comment]
Hi, thanks, I updated the translations.
I also reconfigured Weblate, so now you can always perform translations yourself in the future: https://hosted.weblate.org/projects/betteruntis/translations/
