### ISSUE TITLE
[Feature Request] Option to remove Personal Timetable

### ISSUE THREAD

**Issue by AdditionalRAM** [SapuSeven/BetterUntis#338]
### Problem Statement

Our school provides a single Untis account for all students, not personal accounts, so the Personal Timetable is always empty. This is quite annoying since I have to manually switch to my class' timetable from the side menu.

### Solution Ideas

Option to delete the bookmark for the personal timetable when held, similar to added timetables
Potentially an option to add it back in the "Add Timetable" menu

**Comment by AdditionalRAM** [comment]
Closed because I noticed I can just set a custom personal timetable. Sorry im just dumb lol

**Comment by SapuSeven** [comment]
No worries, glad your problem is solved :)
