### ISSUE TITLE
Der stundenplan soll gezeigt werden aber tut es nicht!!!!

### ISSUE THREAD

**Issue by Maryistcool** [SapuSeven/BetterUntis#339]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 5
Fehlercode: -8509
Fehlermeldung: no right for timetable
```
</details>

**Additional information**

- Android version: _13_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Tut mir leid, dass die App nicht wie gewünscht funktioniert.

Die Fehlermeldung ist aber ganz eindeutig: Der Benutzer ist nicht dazu berechtigt, den Stundenplan anzuzeigen.

Um welchen Stundenplan geht es?
Funktioniert dieser in der original-App?
