### ISSUE TITLE
[Bug Report] Using a lot of storage after few months of usage

### ISSUE THREAD

**Issue by KaktusXY** [SapuSeven/BetterUntis#340]
### Steps to Reproduce

Use the app daily for a few weeks/months

### Expected Result

Not 3GB+ data stored by app

### Actual Result

![screenshot](https://user-images.githubusercontent.com/58702689/214881806-8bc16866-0256-4e76-abec-8b5331df1117.png)

few GB of data

### Android Version

Android 11

### BetterUntis Version

3.5.1 (34)

### Installation Source

F-Droid

**Comment by SapuSeven** [comment]
Sorry that's happening. I suspect these are old log files accumulating over time.
Unfortunately there is no way to delete those yet, but the next major update will not use these kind of log files anymore, so you'll likely have to wait for the update for now.

**Comment by SapuSeven** [comment]
This has been fixed and will be available in the next update. Closing
