### ISSUE TITLE
[Feature Request] More Icons for the Timetable-Settings menu

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#341]
### Problem Statement

There are no icons in the timetable settings menu.

### Solution Ideas

I have some suggests for icons, that can be added in the timetable menu in the settings.

![Screenshot_20230127_121154_BetterUntis](https://user-images.githubusercontent.com/84938977/215074671-44396acd-e302-472e-88d9-f0377d222994.jpg)

Examples (sorted by menu entry)
![Screenshot_20230127_121341_Chrome](https://user-images.githubusercontent.com/84938977/215074822-f1d851e1-a0ad-4ed3-b267-617a119f5dd6.jpg)
![Screenshot_20230127_121421_Chrome](https://user-images.githubusercontent.com/84938977/215074841-6167ead2-52d9-48dd-82fe-ffedabcfb037.jpg)
![Screenshot_20230127_121453_Chrome](https://user-images.githubusercontent.com/84938977/215074866-87f982e6-5e3f-4d32-af70-4bcdcfdda2ad.jpg)
![Screenshot_20230127_121645_Chrome](https://user-images.githubusercontent.com/84938977/215074887-44c694a1-238e-4952-bc4f-80e591eb376d.jpg)
![Screenshot_20230127_121702_Chrome](https://user-images.githubusercontent.com/84938977/215074903-2c2f861f-0653-4407-be50-b98b6c3cb52a.jpg)
![Screenshot_20230127_121730_Chrome](https://user-images.githubusercontent.com/84938977/215074922-c1b1c49b-11d2-495d-a920-1d056cec9e3b.jpg)

These are icons, you can find at Google Fonts (material icons)

**Comment by SapuSeven** [comment]
Done: c0af4ac1dcf2e287b14cbe2a4f3a74b68b31a5cf, a8adf5aac2afffe49b27daf947d2648fb6df1dde
