### ISSUE TITLE
[Feature Request] Little Design suggests 

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#342]
### Problem Statement

I would suggest a few design changes. They are not necessary, but very useful / improving 

### Solution Ideas

I would suggest a few design improvements: 

1. Please remove the click area, because I makes no sense at this point
![Screenshot_20230128_162528_BetterUntis~2](https://user-images.githubusercontent.com/84938977/215276990-e117cadd-8f00-465d-8c63-7f4ee95f54ca.jpg)

~~2. Please add more padding because this would improve the look of the chips~~
![Screenshot_20230128_162540_BetterUntis~2](https://user-images.githubusercontent.com/84938977/215277043-b5b27ec5-6beb-44c0-99b9-bc8908abc68f.jpg)

3. Please remove the highlighted icon by the suggested from material icons (Google fonts)
![Screenshot_20230128_164802_BetterUntis](https://user-images.githubusercontent.com/84938977/215277095-cf14aa1f-a9dc-45df-9a3e-173a6be14123.jpg)
![Screenshot_20230128_170320_Chrome](https://user-images.githubusercontent.com/84938977/215277111-fe6c8d59-ee3e-4f00-a13a-5d57b7d2e912.jpg)

**Comment by lm41** [comment]
Idea 1: 
Do you want the area being removed completly or do you want that the areas clickability is removed.

Idea 2: 
We are using a library (AboutLibrarys from MikePenz) to display those librarys. I will look in the documentation if this is modifiable. If not I can try to write an own LibraryContainer composable. But if I see that this is too much effort for this little layout change, I'm not going to work on that.

Idea 3:
This is in my opinion a good idea, but i don't know what SapuSeven is thinking about it.

**Comment by Lauritz-Tieste** [comment]
> Idea 1: 
> Do you want the area being removed completly or do you want that the areas clickability is removed.
> 
> Idea 2: 
> We are using a library (AboutLibrarys from MikePenz) to display those librarys. I will look in the documentation if this is modifiable. If not I can try to write an own LibraryContainer composable. But if I see that this is too much effort for this little layout change, I'm not going to work on that.
> 
> Idea 3:
> This is in my opinion a good idea, but i don't know what SapuSeven is thinking about it.

1. I mean that the Click ability is removed 
2. I agree completely with your opinion, this a too small think to do such a big effort

**Comment by lm41** [comment]
2. 
![image](https://user-images.githubusercontent.com/59062169/215317837-672d7439-dd8b-4113-8a0f-be542185b01e.png)
Is it a possible solution to align it to the end? Centering it leads to this layout and I think this looks ugly: 
![image](https://user-images.githubusercontent.com/59062169/215317906-affbd62f-e8c2-4042-b8bd-761207201d01.png)

**Comment by Lauritz-Tieste** [comment]
Aligning the items doesn't solve the issue, but it is not necessary so we can ignore it.

The issue is still open because of the other design changes.

**Comment by lm41** [comment]
I implemented all of the suggestions. I've found a simple way to adjust the clips:
![image](https://user-images.githubusercontent.com/59062169/215357111-48f8d8ea-371d-431e-ad9d-e6c402825676.png)
Is it this what you had in mind?

**Comment by SapuSeven** [comment]
To be honest i think the original library license chips look fine. They largely follow Material guidelines for chips only with smaller padding to reduce list item size.
I don't think they should be aligned different to the other text. Right-aligned would also not look bad but i think that's more effort than it's worth.

Regarding the login-button: I'll try it out and see how it looks. I think the login-icon you provided makes more sense. 

As for the first suggestion: we could merge it with the app-version setting below. Right now there's no purpose for there being an extra preference.

**Comment by lm41** [comment]
I've dropped #344 for this. You can delete the current padding by removing the libraryPadding val right above the LibraryContainer.

**Comment by SapuSeven** [comment]
Done: c0af4ac1dcf2e287b14cbe2a4f3a74b68b31a5cf, a8adf5aac2afffe49b27daf947d2648fb6df1dde
