### ISSUE TITLE
[Feature Request] Make error messages fully readable

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#343]
### Problem Statement

If you get a error message (such as no internet connection) you can't read the whole message, because the toast ends.

### Solution Ideas

![Screenshot_20230129_134839_BetterUntis](https://user-images.githubusercontent.com/84938977/215327331-1ec747e4-c5e9-4615-a4dd-eb1477c18794.jpg)

**Comment by SapuSeven** [comment]
You're right. This was only a quick way to implement error feedback. I'll look at it when I get to integrate sentry.

**Comment by SapuSeven** [comment]
Implemented with a89279224fe66c36bdbf8520f2d2755f822fd48f.
Please test it using [the latest debug build](https://api.sapuseven.com/apps/betteruntis/artifact/debug/1035).

**Comment by Lauritz-Tieste** [comment]
It works!
