### ISSUE TITLE
Teachers list is full of old teachers abbreviations/tokens but not in the web-client

### ISSUE THREAD

**Issue by new-on-github** [SapuSeven/BetterUntis#345]
My teachers list is full of old teachers abbreviations/tokens. Therefore you have to scroll a lot to find someone. But in the web-untis-web-client there are only the abbreviations/tokens form this year.

By the way: Thanks for this amazing app.

Tell my please if you need more information for this issue.

**Comment by Lauritz-Tieste** [comment]
Maybe you can clear your Cache or reinstall the app and login another time.

**Comment by new-on-github** [comment]
> Maybe you can clear your Cache or reinstall the app and login another time.

Thanks for your help. I already did this and it doesn't help anything.

**Comment by SapuSeven** [comment]
Did I understand correctly that even if you do a clean login you see the old teachers in the list?
If so, does the Untis Mobile App also show them?

**Comment by new-on-github** [comment]
> Did I understand correctly that even if you do a clean login you see the old teachers in the list? If so, does the Untis Mobile App also show them?

Yes, exactly! I can see a lot old teachers.
The proprietary untis mobile app doesn't show them. There is only the short list from the current year like in the web client.

**Comment by SapuSeven** [comment]
That's interesting. I looked into the data and noticed a property "`active`" on each teacher - maybe it's useful.
Are you able to select the old teachers or are they greyed out?

**Comment by new-on-github** [comment]
> That's interesting. I looked into the data and noticed a property "`active`" on each teacher - maybe it's useful. Are you able to select the old teachers or are they greyed out?

I can select an old teacher, but then it shows no entries in the timetable and tells "no right for timetable" (Error code -8509)

Thanks for your quick reply!

**Comment by SapuSeven** [comment]
Ok, makes sense - but is the text gray too? If so, I have an easy solution for this in mind.

**Comment by new-on-github** [comment]
> Ok, makes sense - but is the text gray too? If so, I have an easy solution for this in mind.

Which text do you mean? The abbreviations/tokens oft he old teachers? No they are shown in the same color as the rest of this years teachers. Even in the dark theme.

**Comment by SapuSeven** [comment]
Alright, thanks for the info. I'll look into it.

**Comment by new-on-github** [comment]
Thanks a lot!

**Comment by SapuSeven** [comment]
Can you please try out [this build](https://output.circle-artifacts.com/output/job/bc4c4784-7b52-4f56-ab37-9ea7b9ec1923/artifacts/0/outputs/apk/debug/app-debug.apk) and see if the inactive teachers are filtered out correctly?

**Comment by new-on-github** [comment]
Thanks a lot. It works perfectly: The teachers from this year are shown only!

**Comment by Lauritz-Tieste** [comment]
This issue should be closed
