### ISSUE TITLE
Clicking on Contributors doesn't show contributors

### ISSUE THREAD

**Issue by SteffoSpieler** [SapuSeven/BetterUntis#346]
### Steps to Reproduce

1. Settings
2. Information
3. Click on Contributors

### Expected Result

Open the browser with the list of all contributors like the other "buttons" do.

### Actual Result

Opens Dialog with the info about GitHubs Privacy Policy and a "show privacy policy" and "cancel" button.

![Screenshot_2023-01-30-15-18-03-105_com sapuseven untis debug](https://user-images.githubusercontent.com/41108856/215503158-fc5dd80b-d432-4454-a17c-49697b94d5c0.jpg)

### Android Version

Android 12

### BetterUntis Version

3.5.1-DEBUG (27902756)

### Installation Source

Own Build

**Comment by SteffoSpieler** [comment]
(oh, also the Cancel Button's Text is weirdly aligned)

**Comment by Lauritz-Tieste** [comment]
![Screenshot_20230130_152720_BetterUntis.jpg](https://user-images.githubusercontent.com/84938977/215504382-cb276738-1468-489e-b927-3388035e1e76.jpg)

On MY device, I can't reproduce the bug. It is working perfectly and there is an ok button. If you click it, it will show all the contributors.

![Screenshot_20230130_152903_BetterUntis.jpg](https://user-images.githubusercontent.com/84938977/215504860-415c918f-6b84-4fe5-bf5d-615f67ba0bcb.jpg)

**Comment by SteffoSpieler** [comment]
huh.. I can try to build a newer version of the material-ui-3 branch in a few hours. But if it helps, I'm using an Xiaomi Mi 10T Pro with MIUI 13 (Android 12)

**Comment by Lauritz-Tieste** [comment]
If you want, you can try this apk, I have extracted from my installed version of betteruntis. You can download the apk with this link (available until 2023-02-07) https://we.tl/t-YMPvBB7XeN

**Comment by SapuSeven** [comment]
Hi, yeah I noticed that issue as well and fixed it in 55bf014c9b0630f123b005e78a472777eb68b6f0.
You can get the latest APK from [CircleCI](https://output.circle-artifacts.com/output/job/c3e9f940-5df4-4c55-ae32-c8b5b9744f79/artifacts/0/outputs/apk/debug/app-debug.apk).

**Comment by SteffoSpieler** [comment]
> Hi, yeah I noticed that issue as well and fixed it in 55bf014c9b0630f123b005e78a472777eb68b6f0.
> You can get the latest APK from [CircleCI](https://output.circle-artifacts.com/output/job/c3e9f940-5df4-4c55-ae32-c8b5b9744f79/artifacts/0/outputs/apk/debug/app-debug.apk).

Sweet. Tried it and it works now!

Small question - is that url just this artifact for this version or in general for the latest build? And if not - is there an url to always download the latest version? Don't want to uninstall the version again because it was build by someone else 😅

**Comment by SapuSeven** [comment]
The CircleCI-Link is just for this version. I don't think there's public access to every build. Usually the latest debug build can be downloaded from my website, but the material 3 update is being worked on another branch and doesn't get uploaded there. If you really want to, it should be pretty easy to build it yourself ;)

**Comment by lm41** [comment]
![Screenshot_20230131-230422-614.png](https://user-images.githubusercontent.com/59062169/215894420-7ac74f34-9982-4ae0-bec3-90da89564d84.png)

I think your site does not work. Checked with Firefox + Chrome and for the network error also from the Tor network.

**Comment by SteffoSpieler** [comment]
> The CircleCI-Link is just for this version. I don't think there's public access to every build. Usually the latest debug build can be downloaded from my website, but the material 3 update is being worked on another branch and doesn't get uploaded there. If you really want to, it should be pretty easy to build it yourself ;)

ah, I see. As I already mentioned I already built the "original" Version used in this ticket. So.. yeah. I guess that isn't a problem :D
Still thank you! ^^

**Comment by SapuSeven** [comment]
> I think your site does not work. Checked with Firefox + Chrome and for the network error also from the Tor network.

Fixed now :)
