### ISSUE TITLE
App keeps crashing 

### ISSUE THREAD

**Issue by McFaul4** [SapuSeven/BetterUntis#347]
### Steps to Reproduce

Turn on the auto- do not disturb Feature and wait for a lesson.

### Expected Result

It should turn do not disturb on and you should still be able to use the app...

### Actual Result

App crash's 

### Android Version

Android 11

### BetterUntis Version

3.5.1

### Installation Source

F-Droid

### Additional information

![Screenshot_2023-01-30-16-41-29-67](https://user-images.githubusercontent.com/116670013/215523347-a2e19adc-008f-4c4f-a723-88aa575c2122.jpg)

**Comment by SapuSeven** [comment]
Thanks for the detailed error report.

This looks like the same issue as #275.
It's an issue with Android 12+ that has already been fixed for the next release, but unfortunately the only solution for now is to turn off auto-mute and wait for the material-3 update to be released.

**Comment by McFaul4** [comment]
But I have Android 11. And what do you mean by waiting for the material-3 update? Is this an update of the BetterUntis app or an Android Update? Cause my Device won't get any System updates xD

**Comment by lm41** [comment]
The Material 3 Update is an upcoming app update tracked in #290

**Comment by SapuSeven** [comment]
@lm41 is correct. Only an app update is needed. I'm not completely sure which Android versions are affected by the issue you described, but the material 3 update will fix it.

**Comment by McFaul4** [comment]
I installed the beta and the bug still remains... Have missed something?

Anyways, thanks for the help 🙏

**Comment by lm41** [comment]
I've tested it on my Android 11 Emulator (fresh installed) and it works. Do you have granted BetterUntis DoNotDisturb access in the Android settings(should be "Apps & Notifications" - > "Advanced" -> "Special app access" -> "Do Not Disturb access")?

**Comment by McFaul4** [comment]
Oh, I just checked my Android version and remembered I have Android 12. Sorryyyy🥲😂

**Comment by McFaul4** [comment]
Ok, so I updated to the 3.5.1 and the App doesn't crash anymore, but neither does my phone mute itself..
Should I open a new issue?😅

**Comment by SapuSeven** [comment]
I think you should wait until the material update is finished - if the feature still doesn't work correctly, feel free to open a new issue.
