### ISSUE TITLE
Dark mode: follow System preference

### ISSUE THREAD

**Issue by McFaul4** [SapuSeven/BetterUntis#348]
### Problem Statement

At the time you can only turn Dark Mode on, off or have it turn automatically on, by the battery percentage.

### Solution Ideas

Would by nice, if it follows the system theme :) (of course as a option to opt out)

**Comment by lm41** [comment]
This has been implemented with #290 (the material design 3 update).

**Comment by McFaul4** [comment]
Oh, sry for opening this issue!

**Comment by lm41** [comment]
> Oh, sry for opening this issue!

You couldn't have known that. Better one feature request too much than too few :)
