### ISSUE TITLE
Teacher abbreviation to teacher name

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#349]
### Problem Statement

Sometimes you see abbreviations in school. It would be a good idea if you could type the abbreviation into BetterUntis and get the teacher's full name as an answer.

This is a feature that is not necessary but it will be useful in every school day

**Comment by SapuSeven** [comment]
You can just use the teacher list for that - it shows the abbreviated names. You can even search that list. When you select a teacher, it displays their timetable and shows the full name in the top bar.

**Comment by Lauritz-Tieste** [comment]
I agree with you. With this information it really seems unnecessary to me to introduce a function.
