### ISSUE TITLE
[Bug Report] Crashes after selecting school

### ISSUE THREAD

**Issue by 7RST1** [SapuSeven/BetterUntis#35]
**Description**
App crashes after choosing which school to use.

**Actual behavior**
I am not sure how to reproduce it, as the app seems to work fine for other users. After it's "finished" loading it either crashes with a brief error message or goes back to the main launch activity. I tried to capture the crash message. It's attached below.

**Expected behavior**
After the app finishes loading I would expect it to go to the timetables for that particular school.

<details>
  <summary><b>Screenshots</b></summary>
This is the brief crash message that appears for a split second:

![Screenshot_20191227-222352](https://user-images.githubusercontent.com/16783057/71542462-278ace80-2967-11ea-8539-4500826da0b8.jpg)
</details>

**Additional information**
 - Android 10 (OnePlus 7 Pro)
 - 3.2.1

**Comment by SapuSeven** [comment]
That's a weird error...
I think I'll have to implement a better error reporting system for more details. That could take a few days..

**Comment by 7RST1** [comment]
If anyone want to troubleshoot it themselves, here is the school-ID:
1346600
Anonymous login
There might be something wrong/special with the school itself and not the app, but I can't figure it out. Maybe someone else can.

**Comment by SapuSeven** [comment]
Thanks, on it

**Comment by SapuSeven** [comment]
Finally figured it out. Should be fixed in 644675fd29788dcadad156608ce43a3a0c6cb0c7 ([build#313](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=313))

**Comment by 7RST1** [comment]
Well, something changed;
Now it doesn't crash, but it gives me "An unknown error happened while adding the user."

**Comment by SapuSeven** [comment]
Alright, should be finally fixed in 1f1e63ac2d2b14842d4d21fdf8f00e3db50e8396 ([build#319](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=319)).

You may have to clear all app data first if it still doesn't work.

**Comment by 7RST1** [comment]
Can confirm that it works now! Thank you👍
I have another unrelated bug. Will be opening [another bug report](https://github.com/SapuSeven/BetterUntis/issues/57).
