### ISSUE TITLE
[Bug Report] Username and Password fields in setup don't allow (system) autofill

### ISSUE THREAD

**Issue by SteffoSpieler** [SapuSeven/BetterUntis#350]
### Steps to Reproduce

1. Search for school and press on one
2. Hold on the username (or password) input field
or
Tap on the username field - Google GBoard should show the "autofill with ..." prompt (for me at least)

### Expected Result

See button called `Autofill` on the right of "paste". And on my keyboard (Google GBoard) there should be an "Autofill with ...".

Here's how it should behave like (in another app):
![IMG_20230201_004621](https://user-images.githubusercontent.com/41108856/215909620-92daa684-93f0-4fcc-9cda-22bfdffddfca.jpg)

### Actual Result

Apparently the system doesn't detect that those input fields are username / password input fields.
![IMG_20230201_003530](https://user-images.githubusercontent.com/41108856/215908850-00cb1868-ca0d-4fe4-8e84-171321d4f774.jpg)

### Android Version

Android 12 - MIUI 13

### BetterUntis Version

3.5.1-DEBUG (27920130)

### Installation Source

Own Build

**Comment by SapuSeven** [comment]
I added autofill with 5fec0997828a1b041fb9a4b79526460d122df363.
Unfortunately, as reported in https://issuetracker.google.com/issues/176949051, the feature only works with Google Autofill.
I hope there's a fix released to compose soon.

**Comment by Lauritz-Tieste** [comment]
In the latest beta version, I can use my third-party password manager DASHLANE as well as the Google Passwort Manager to fill in the login data.


![Screenshot_20230713_183003_BetterUntis~2.jpg](https://github.com/SapuSeven/BetterUntis/assets/84938977/252b0e36-3a7a-4dd4-acac-1d7078140e0e)

**Comment by SapuSeven** [comment]
I can confirm.
Looks like this finally got fixed upstream.
