### ISSUE TITLE
[Feature Request] Show "Taking place as a video conference" in details page

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#351]
### Problem Statement

If I display information about a subject where the teacher has set "takes place as a video conference", this important information is displayed in UntisMobile, but not in BetterUntis.

### Solution Ideas

Actually, an entry for "takes place in a video conference" should also be displayed on the detail page in Betteruntis.

**Screenshot of UntisMobile:** 
![untismobile](https://user-images.githubusercontent.com/84938977/216096139-3366208a-2ec5-4d2d-870e-f9f9cc195dcc.jpg)

**Screenshot of Betteruntis:** 
![betteruntis](https://user-images.githubusercontent.com/84938977/216096687-9704ee2a-7c16-4482-8604-847f6dad56d6.jpg)

**Comment by TobiFlobi26** [comment]
In the newest debug version (v4.0.0-beta01-DEBUG+27939753.1035) it now shows an "online lesson" notice for every lesson, even though they are not marked so in the original untis app.

**Comment by Lauritz-Tieste** [comment]
It's fixed in the newest version
