### ISSUE TITLE
[Crash Report] Notifications not working on Android 12

### ISSUE THREAD

**Issue by SirZuckerWahl** [SapuSeven/BetterUntis#353]
[logs-1675925681687.zip](https://github.com/SapuSeven/BetterUntis/files/10695002/logs-1675925681687.zip)

**Additional information**
Notifications don't work after upgrade to Android 12.

- Android version: _12_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.packageinstaller_

**Comment by SapuSeven** [comment]
Hi, please try going to your "System Settings -> Apps -> BetterUntis -> Permissions -> Notifications" and check if you enabled notifications. If this still doesn't work, you'll probably have to wait for the new 4.0.0 update that will soon be released.

**Comment by SirZuckerWahl** [comment]
I will wait for the new version. Hopefully my phone will be able to change "don't disturb" mode during lessons again.
Thanks for good work 😃

**Comment by SapuSeven** [comment]
Alright, this was actually the same problem as #275 - you can expect the new version 4.0.0 to work with auto-mute and notifications (available on Google Play Beta or [on my Website](https://sapuseven.com/app/BetterUntis/) if you want to test it out).
