### ISSUE TITLE
[Bug Report] Lesson information is not displayed

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#354]
### Steps to Reproduce

1. Click on any subject

### Expected Result

The lesson information should be shown

### Actual Result

when I open BetterUntis and click on any subject, no lesson information is displayed in the dialog.

### Android Version

Android 13

### BetterUntis Version

BetterUntis 3.5.1 and 4.0

### Installation Source

Installed over GitHub Releases .apk (V4.0) and Google Play Store (3.5.1)

**Comment by Lauritz-Tieste** [comment]
https://user-images.githubusercontent.com/84938977/218282117-0832b06a-5173-40fc-b4d4-411df1e96cf5.mp4

**Comment by Marco-9456** [comment]
> 20230211_222749.mp4

It's also reproducible on my side.

**Comment by SapuSeven** [comment]
Should be fixed with 876c9fae9477808bb22e9d9756f5034ad53b9b6b.
You can download [the latest debug build](https://api.sapuseven.com/apps/betteruntis/artifact/debug/1035) to try it out.

**Comment by Marco-9456** [comment]
> Should be fixed with `876c9fa`.

Funny enough it's working now for some reason 💀

**Comment by SapuSeven** [comment]
> Funny enough it's working now for some reason 💀

That's because I fixed it ;)

**Comment by Marco-9456** [comment]
> 

Haha i know but i meant in the previous build that i used (BetterUntis 4.0.0-beta01)

**Comment by SapuSeven** [comment]
Yeah it was a weird mismatch between what the app thought the current week was and what was actually the current week, so sometimes it matched and worked, sometimes it didn't match and the dialog is empty, depending on what day of the week it was and on which page you were.
But I'm glad it's working now.
