### ISSUE TITLE
Keyboard overlaps input at login process

### ISSUE THREAD

**Issue by MatsG23** [SapuSeven/BetterUntis#356]
In the login view, the keyboard overlaps the password and username (partially) input. This is not the case in e.g. in the school selection view.
The UX would be better if these fields would be at a higher position when the keyboard is open (maybe a scroll layout?). It is annoying to type into an input field without being able to see what you are typing immediatly. 

![screenshot-login](https://user-images.githubusercontent.com/60609373/219085840-c29ccc47-acaa-4966-b3f3-7e8f082956bf.png)
![screenshot-school-search](https://user-images.githubusercontent.com/60609373/219085850-f92f9463-1ba2-48eb-9d91-4d55395953a5.png)

**Comment by SapuSeven** [comment]
Fixed with e72e47ee1b549d05ad50f339dee77d163a7377c6

**Comment by MatsG23** [comment]
The top and bottom bars on the login page are white now (do not adapt to system theme).

-------- Original-Nachricht --------
Am 16. Feb. 2023, 03:25, schrieb SapuSeven :

**Comment by SapuSeven** [comment]
No worries, I'm currently working on updating the material 3 library. Stay tuned
