### ISSUE TITLE
[Feature Request]: Excuse absence via BetterUntis - modul "Klassenleitung"

### ISSUE THREAD

**Issue by new-on-github** [SapuSeven/BetterUntis#359]
### Problem Statement

Now the teacher can already tick the absence/presence of pupils via the BetterUntis-App. But it would also be nice to enter excuses. This would be the modul with the German name "Klassenleitung".

This request is a addition to the request #187 :
https://github.com/SapuSeven/BetterUntis/issues/187

### Solution Ideas

Sorry, I don't know how to help.

I also know this is a lot of work. And it is some sort of a curse of your amazing work, that the user like me requests even more features. Therefore if you cannot realize it, it's also fine. 

Thanks for your work.

**Comment by SapuSeven** [comment]
I will combine this with #376, as it looks related to managing absences/excuses.
