### ISSUE TITLE
[Bug Report] Not all lessons showing

### ISSUE THREAD

**Issue by ghost** [SapuSeven/BetterUntis#36]
**Description**
For me only lessons 1 to 5 are showing. What it looks Like:
![Screenshot_2020-01-06-21-58-17-375_com sapuseven untis](https://user-images.githubusercontent.com/59582057/71848397-a9999680-30cf-11ea-8f9a-f85dbfc229d5.jpg)
How it should be:
![Screenshot_2020-01-06-21-58-55-954_com grupet web app](https://user-images.githubusercontent.com/59582057/71848467-d057cd00-30cf-11ea-8263-fc65d5ed74d1.jpg)

**Actual behavior**
Deleted all files and Reinstalled the app many Times, nothing Changed. I Think the Error comes Up because my school has to many Lessons at the Same time showing.

**Expected behavior**

<details>
  <summary><b>Screenshots</b></summary>

  Add screenshots here to describe the problem.
  Please include screenshots of the original Untis Mobile app if applicable.
</details>

<details>
  <summary><b>Logs</b></summary>

  Add a detailed stack trace / crash log here if applicable.
</details>

**Additional information (please replace)**
 - Android Version 10/MiUi 11
 - BetterUntis version 3.2.1(17) 

i was the Guy who requested the feature to only Show one day at the time.

**Comment by SapuSeven** [comment]
That's a weird issue...

Would you mind sharing your school id for anonymous access?

**Comment by ghost** [comment]
I am new on github is it possible to write a private Message for that?

**Comment by SapuSeven** [comment]
No, you can write me an email: betteruntis@sapuseven.com

**Comment by spaetz** [comment]
Here is another case of a missing course. Compare the screenshot of webuntis with the screenshot of Betteruntis (the 5. Block *was* showing up in Betteruntis this morning if I remember correctly...)
![Webuntis](https://user-images.githubusercontent.com/63132/72071060-38362f80-32eb-11ea-8951-176844aa06c8.png)
![Betteruntis](https://user-images.githubusercontent.com/63132/72071133-63208380-32eb-11ea-88cb-e03fa0b29ad4.png)

**Comment by SapuSeven** [comment]
That's really weird. Unfortunately your school doesn't allow anonymous access, so I think you'll have to wait until I finish the advanced error reporting system (as mentioned in #35)

**Comment by phibr0** [comment]
I opened this report, but I changed my account.
Would you investigate my problem if I provide you with the full credentials?

**Comment by SapuSeven** [comment]
Sorry for the wait, school's pretty busy atm.

But yes, I would probably be able to solve your issue pretty soon if you send me your credentials.
Remember you can always change the app key on the WebUntis homepage.

**Comment by SapuSeven** [comment]
Fixed in 64cbdfff441f2e2577378b2a84fc3ed2c81085eb.
~~Unfortunately my build server is currently not working, so you'd have to wait for the next update (or build yourself).~~
You can wait for the next update or use [build#236](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=236) from my website.

**Comment by phibr0** [comment]
It works but the lessons are split up even though they shouldn't. It happens with all lessons after the fourth.

It's not a big problem but it would be cool if it gets fixed too.

![Screenshot_2020-01-24-14-07-04-197_com sapuseven untis debug](https://user-images.githubusercontent.com/59741989/73071359-d19c3e80-3eb2-11ea-94c1-3bde31178a40.jpg)

**Comment by SapuSeven** [comment]
Is the end time of the 5th/7th lesson the same as the start time of the 6th/8th lesson?

**Comment by phibr0** [comment]
It should. In the original Untis Mobile App they arent splitted
