### ISSUE TITLE
[Bug Report] Automatic scrolling when clicking on the profile

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#360]
### Steps to Reproduce

https://user-images.githubusercontent.com/84938977/219494345-5f29392f-48c7-45df-8d49-5f98be1aa079.mp4

Click in your user icon multiple times

### Expected Result

This shouldn't go to the next week!

### Actual Result

It goes to the next week. You can repeat the process infinite times. This makes absolutely no sense

### Android Version

Android 13

### BetterUntis Version

4.0.1 beta-2

### Installation Source

Google Play

**Comment by Lauritz-Tieste** [comment]
Maybe this could help:

I once heard in a tutorial that when state changes occur when the screen is rotated (or in this case), the user interface is rebuilt. That could be related to the error

**Comment by SapuSeven** [comment]
Yes, this is a bug with the WeekView library.
It should be fixed when WeekViewCompose is implemented.

**Comment by Lauritz-Tieste** [comment]
This is fixed in version [4.1.0-beta01](https://github.com/SapuSeven/BetterUntis/releases/tag/4.1.0-beta01)
