### ISSUE TITLE
Add function to Add absences 

### ISSUE THREAD

**Issue by W113565456** [SapuSeven/BetterUntis#364]
### Problem Statement

In can't add absences in Betteruntis. 

### Solution Ideas

Please add an function to Add absences.

**Comment by SapuSeven** [comment]
If you have the required permissions as a teacher, you can tap on a lesson and go to "absences". This shows a list of all students, where you can mark them as absent by tapping on them. Afterwards, use the check mark button on the bottom right to submit.

**Comment by Cameo007** [comment]
In normal Untis you can also add absences via the parent's account.

**Comment by SapuSeven** [comment]
This will be tracked in #376
