### ISSUE TITLE
[Feature Request] Dont't treat cancellations for other classes than mine as irregular

### ISSUE THREAD

**Issue by spaetz** [SapuSeven/BetterUntis#37]
Currently, if a course is cancelled only for a different class, Better Untis will show this in the 'irregular' color scheme although nothing actually changes for me. If I select the 'use school colors' scheme, the course will correctly show up in the normal color...update, just to clarify. I am talking about courses in which multiple classes are supposed to participate, like a Big Band or a school assembly.

**Comment by SapuSeven** [comment]
I think I won't implement this feature for now.
It's a really niche use case which would require a rather complicated solution.
Feel free to open up a discussion if you think this is still needed.
