### ISSUE TITLE
Android 13: App stürzt ab, wenn "Automatisches Stummschalten" aktiviert wird

### ISSUE THREAD

**Issue by jw243** [SapuSeven/BetterUntis#372]
### Steps to Reproduce

1. Einstellungen > Allgemein > Automatisches Stummschalten aktivieren.
2. In den Android-Einstellungen BetterUntis Zugriff auf DoNotDisturb-Modus gewähren.
3. Erneut in Einstellungen > Allgemein > Automatisches Stummschalten aktivieren, da der Schalter immer noch auf "aus" steht.

### Expected Result

Die App sollte weiterhin funktionieren.

### Actual Result

App stürzt ab und lässt sich auch nicht mehr starten, bis sie zurück gesetzt wird.

### Android Version

Android 13

### BetterUntis Version

3.5.1 (34)

### Installation Source

F-Droid

### Additional information

LineageOS mit MicroG 20
Magisk 25.2

**Comment by SapuSeven** [comment]
No worries, this has been fixed in the newest 4.0.0-beta-versions and will be available soon.
See #275
