### ISSUE TITLE
Use username as profile name if none is given

### ISSUE THREAD

**Issue by sertonix** [SapuSeven/BetterUntis#374]
I tried the latest beta and it seemed quite good.
One thing I saw that when no profile name is given only empty space is shown. It would be good if some other value line the username would be used.

**Comment by Lauritz-Tieste** [comment]
If you don't fill out the optional field for the username, my "official" Untis username will be displayed. Therefore it is probably an incorrect Untis configuration if nothing is displayed.

**Comment by sertonix** [comment]
If that is the case I will close this issue.
