### ISSUE TITLE
Some rooms not showing up as they should

### ISSUE THREAD

**Issue by RedCommander735** [SapuSeven/BetterUntis#377]
### Steps to Reproduce

Open my personal timetable

### Expected Result

MSS12 shows up as the room below german lessons(D_GK_3).
![Screenshot_2023-04-25-06-41-43-71_3b0cae95b78a88b305a0908c953dd949](https://user-images.githubusercontent.com/40245965/234176989-ebd91676-ca70-4c17-b9a1-e5975c0a6b43.jpg)

### Actual Result

There's just a question mark
![Screenshot_2023-04-25-06-35-35-32_b158fca0b71165baed59eef517695f4e](https://user-images.githubusercontent.com/40245965/234177088-9d8551d0-02ec-41f2-b896-90b495a93b15.jpg)

### Android Version

12

### BetterUntis Version

4.0.0beta4

### Installation Source

Google Play

### Additional information

I tried looking at the same lessons in while with an anonymous login and there the room showed up.

**Comment by SapuSeven** [comment]
Please try to update your profile data by editing your profile and logging in again.

**Comment by RedCommander735** [comment]
That seems to have worked. I removed the profile and logged in again. I also changed the e-mail address on my Untis profile before logging back in since I wanted to do that anyway, and I didn't know if you meant my Untis profile or just the profile in BetterUntis.
