### ISSUE TITLE
[Feature Request] show changes for irregular courses in timetable.

### ISSUE THREAD

**Issue by spaetz** [SapuSeven/BetterUntis#38]
If e.g. a room has been changed, I would like to see this directly in the timetable view (e.g. 111 ~~222~~) just like OpenUntis and the official Untis apps do. Currently,  I have to click on the details popup to see what actually has changed.

Thanks for BetterUntis, it is great!

**Comment by SapuSeven** [comment]
Right, this will probably be more difficult than it seems.

**Comment by SapuSeven** [comment]
Implemented in 7846686b63ce6c0409445d00e158ec4c1700d04a.

**Comment by spaetz** [comment]
cool, thanks a lot'
