### ISSUE TITLE
[Feature Request] better support for class-only accounts

### ISSUE THREAD

**Issue by wamserma** [SapuSeven/BetterUntis#386]
### Problem Statement

Our school issued as single user/password combination per class, which I can successfully use when creating a new profile.

When I open the app, the view defaults to the personal timetable and I receive an "access denied" error:

Request-ID:12
Error Code: -8509
Message: no right for timetable

When I open the burger menu, I can select the class timetable from the list of timetables and I see all information as expected.

(App Version: 3.5.1 (34) via f-droid)

### Solution Ideas

any of these would improve the UX:
- allow to set a default timetable in profile settings 
- allow to hide personal timetable/set an option only use the class timetable in profile settings
- remember the last timetable viewed to reopen it when the app is reopened

**Comment by SapuSeven** [comment]
Hi, sorry for taking so long to get back to you on this issue.
There is in fact already an option to do all that you tried to do:
In settings, go to Timetable -> Custom Personal Timetable. There you can select your class to act as a "personal timetable".
