### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#387]
### Problem Statement

![Screenshot_20230520_113041_BetterUntis~3](https://github.com/SapuSeven/BetterUntis/assets/84938977/c82a648e-7904-4d22-b9c0-e74dc15294f1)

### Solution Ideas

translate the untranslated text and fix the new-line bug

**Comment by SapuSeven** [comment]
The missing translation was addressed in 82424b353c381c92fe32e2e772d94338b71c9eb8.

For the bottom nav issue, I don't have a good solution.
The [Material 3 Guidelines](https://m3.material.io/components/navigation-bar/guidelines#5a0e52ea-eb3f-42ef-96a4-160c7faf3c93) specifically discourage wrapping or truncating text.
The only real possibility would be an alternative translation (e.g. "Eigener"), or maybe an abbreviation ("Persönl."), keeping in mind that this will also affect the fullscreen dialog variant.
I'd be happy about your input.

**Comment by lm41** [comment]
If there is a way to determine the screen width at runtime we could dynamicly abreviate the text.

**Comment by Lauritz-Tieste** [comment]
Maybe you can make this a Fullscreen dialog
