### ISSUE TITLE
[Bug Report] School search or login not working

### ISSUE THREAD

**Issue by SapuSeven** [SapuSeven/BetterUntis#388]
### Steps to Reproduce

1. Add a new profile
2. Enter any text in the school search field

### Expected Result

A list of results should be displayed

### Actual Result

No results are displayed, no matter the input

### Android Version

any

### BetterUntis Version

any

### Installation Source

Other

### Additional information

This happens because Untis changed something with the endpoint for school search.
The request structure is unchanged.

Previously used endpoint: `https://mobile.webuntis.com/ms/schoolquery2/`
New endpoint (Untis Mobile): `https://schoolsearch.webuntis.com/schoolquery2`

This also breaks logging in.

**Comment by lm41** [comment]
~~Was only the schoolsearch endpoint moved?~~ Sorry missread

**Comment by lm41** [comment]
My browser is connecting to `https://mobile.webuntis.com/ms/schoolquery2` 
![image](https://github.com/SapuSeven/BetterUntis/assets/59062169/5e6827a7-f422-444a-872d-85e8d6474d0e)

**Comment by SapuSeven** [comment]
Actually I noticed BetterUntis used `https://mobile.webuntis.com/ms/schoolquery2/` (notice the slash at the end).
This isn't working anymore.
Regardless, I will update the URL to match Untis Mobile.

**Comment by SapuSeven** [comment]
Fixed in the latest release (4.0.0).
