### ISSUE TITLE
Swiping skips some days in timetable

### ISSUE THREAD

**Issue by spaetz** [SapuSeven/BetterUntis#39]
BetterUntis 3.2.1 from Fdroid here on an Android 7.1.2.

I have set BetterUntis to only show "1" day of the week, ie today. (Note: The bug is gone if I select 2 days already.). When I swiped today (a Thursday) to the previous day, the schedule of Monday shows up. If I swipe once more, the very same Monday shows up. A third swipe will also show the very same Monday, a 4th swipe will then show Friday of last week.
The behavior is the same for the previous week then. (Mon-Wed all show the Monday schedule). If I swipe to the right, ie to tomorrow Friday, the correct day is shown.

So swiping days is like this:
Monday Jan 6 -> Monday Jan 6 -> Monday Jan 6 -> Thu Jan 9 -> Fri Jan 10 -> Mon Jan 13 -> Mon Jan 13 -> Mon Jan 13 -> Thu  Jan 16 -> Fri Jan 17 -> ...

I hope you get the behavior I described, happy to clarify or provide a screencast is necessary.

**Comment by SapuSeven** [comment]
Can confirm. Will work on this.

**Comment by SapuSeven** [comment]
Fixed in c34bd10cee547ccc1c3a5b507d9bbcd3cf3ff6e3 ([build#236](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=236)).
