### ISSUE TITLE
[Feature Request] Material You themeable icons

### ISSUE THREAD

**Issue by alexcoder04** [SapuSeven/BetterUntis#390]
### Problem Statement

In Android 13, app icons can be themed to match the overall system colorscheme.
Right now, BetterUntis seems not to support themeable Android 13 icons.

![photo1686681380](https://github.com/SapuSeven/BetterUntis/assets/70093931/ed4b063e-c37e-4a83-bd88-10f4aaadc6e4)

**Comment by lm41** [comment]
This has already been added in the newest betas.
