### ISSUE TITLE
[FYI] betterUntis as installed from github release called "BetaUntis"

### ISSUE THREAD

**Issue by jolly-jump** [SapuSeven/BetterUntis#391]
Hi. This is not a bug report. However you seem to have introduced a renaming in the debug-version of BetterUntis to "BetaUntis" and replaceing the icon with a grey icon.
I like the idea.

However, since the 4.0.0 release seem to be not a debug-version, would it rather be better to call 4.0.0 "BetterUntis"?
Or is the plan to publish it via F-Droid and make sure, there it is called "BetterUntis"?

Greetings!

**Comment by SapuSeven** [comment]
Thanks for paying attention :)
The name "BetaUntis" is used for debug builds, so it's not version dependent.

However, now that you mentioned it, I noticed that the GitHub release wrongly uses the debug build as well - I'll fix that soon.

Do you see any other place where the wrong build is used?

**Comment by jolly-jump** [comment]
You're welcome :)
> However, now that you mentioned it, I noticed that the GitHub release wrongly uses the debug build as well - I'll fix that soon.

That is, what I meant to report, probably.

I can't find any other "app-debug.apk" except for the one where I would have expected them anyway (Title: 4.0.0-beta* etc.)

If by "any other place" you mean external sites that host BetterUntis like F-Droid - I did not check and would not know where to look. As long as the f-droid.org repo is correct, I am happy.

**Comment by SapuSeven** [comment]
Future GitHub releases should now use the correct build.
I also went ahead and updated the attached file for 4.0.0 to the proper version.
Other sources should be fine. Thanks!
