### ISSUE TITLE
[Bug Report] Can't login without password or access key

### ISSUE THREAD

**Issue by Krintni** [SapuSeven/BetterUntis#393]
### Steps to Reproduce

1. Add profile
2. Choose your school
3. Enter your username
4. Click login

### Expected Result

The login is successful and the timetable is shown.

### Actual Result

A message that the access key/password field may not be empty appears even though school doesn't require this field in order to login.
![screenshot](https://github.com/SapuSeven/BetterUntis/assets/132835834/c51c1f15-3232-4020-aeda-bf222e422e97)

### Android Version

Android 13

### BetterUntis Version

4.0.0 (28111660)

### Installation Source

Google Play

### Additional information

My school doesn't require us to enter a password to login to our Untis account. Logging in without a password in BetterUntis worked in the past but now it doesn't because BetterUntis expects the password field to be filled.

**Comment by SapuSeven** [comment]
Thanks for your report. 

Would you be comfortable with sharing your username with me directly? That way I could test it myself.
If so, please send it to sapuseven@gmail.com or via [Matrix](https://matrix.to/#/@sapuseven:sapuseven.com).
Otherwise, don't worry, I'll get a new version ready for you to test soon.

**Comment by Krintni** [comment]
Hey I'll just test the new version. Simply mention me when you're ready.

**Comment by SapuSeven** [comment]
I just published a new Beta version: 4.0.1
Please check if it works for you now.

**Comment by Krintni** [comment]
It works now. Thank you very much!
