### ISSUE TITLE
[Feature Request] Show timetable of whole weak instead of 1 or 2 days

### ISSUE THREAD

**Issue by TabForce** [SapuSeven/BetterUntis#394]
### Problem Statement

Thank you for BetterUntis! It's really doing a great job.
Unfortunately my lessonplaner just wants us teachers to have data from today and tomorrow, not the whole week.
Can Betteruntis show the whole timetable of one week based on old data? So I wouldn't have so much hassle with remembering every single lesson in one week.
Thank you

### Solution Ideas

Show expected lessons, if no data is available, in semi transparent colors based on data from last week

**Comment by lm41** [comment]
In `Settings -> General -> Week Display Settings` you can enable `Snap to Days` and set `Days to display` to 2. Is this what you were asking for?

**Comment by TabForce** [comment]
Am Dienstag, 20. Juni 2023, 11:19:24 CEST schrieb lm41:
> In `Settings -> General -> Week Display Settings` you can enable `Snap to
> Days` and set `Days to display` to 2. Is this what you were asking for?

Thanks for your quick reply,
quick example: On Monday, I can only see Monday and Tuesdays lessons - untis 
(serverside) only supplies these to days. 
Lessons from wednesday to friday aren't shown. The Untis-Admin says they won't 
say that on serverside.
I wan't wednesdays to fridays lessons to be shown in betteruntis based on data 
from last week. Usually lessons don't differ from week to week, so they're 
reliable most of the time.

Thank you
Gorden

**Comment by SapuSeven** [comment]
Hi Gorden,
unfortunately I think this is a lot of effort to mitigate an issue that only happens for a single, arguably misconfigured Untis server.
This should be fixed on Untis' side instead.
