### ISSUE TITLE
Add advanced setting to modify "mobile.webuntis.com"

### ISSUE THREAD

**Issue by Perflyst** [SapuSeven/BetterUntis#4]
For privacy reasons I use and provide a proxy for the untis site and API: https://github.com/Perflyst/OpenUntis/blob/master/docs/setup-proxy.md

"mobile.webuntis.com" was not used in the legacy app but is used in this one. Please add some "advanced user" option or similar to be able to change this URL.

**Comment by SapuSeven** [comment]
I started implementing this feature in the recent commits. Can you setup your server to work with `mobile.webuntis.com` to test this feature? The app connects to `/ms/schoolquery2` and `/ms/app` on this host.

**Comment by Jan200101** [comment]
works for me

**Comment by SapuSeven** [comment]
Great, I'll close this for now.

@Perflyst feel free to re-open the issue if you have any further problems.

**Comment by Perflyst** [comment]
mobile.openuntis.perflyst.de is deployed, will test it later if I can compile the apk
