### ISSUE TITLE
[Crash Report]

### ISSUE THREAD

**Issue by derjoshder** [SapuSeven/BetterUntis#402]
<details>
<summary>Logs</summary>

```
Bitte füge die komprimierten Log-Dateien als Anhang hinzu.
Diese wurden hier gespeichert: `/storage/emulated/0/Android/data/com.sapuseven.untis/files/logs-1690977250306.zip`
```
</details>

**Additional information**

- Android version: _9_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.google.android.packageinstaller_

**Comment by Lauritz-Tieste** [comment]
Please update the app e.g. in the Play Store or with GitHub releases to version 4.x. The version includes many crash fixes.

**Comment by derjoshder** [comment]
Thank you, that helped!
Had to deinstall completely, cache and data purging didn't help, update was not possible without deinstall.
F-Droid doesn't have the 4.x Version though...
Thank you!
Josh

02.08.2023 14:06:14 Lauritz Tieste ***@***.***>:

**Comment by Lauritz-Tieste** [comment]
perfekt! Then you can close this issue
