### ISSUE TITLE
[Feature Request] Office365-Login-Button

### ISSUE THREAD

**Issue by othielking** [SapuSeven/BetterUntis#405]
### Problem Statement

As implemented in webuntis.com, can you add a button which uses webbased Login for Office365/Microsoft365?
Thanks! :)

### Solution Ideas

-

**Comment by SapuSeven** [comment]
I haven't looked into this in detail, but usually it's impossible to integrate single-sign-on from 3rd parties like Microsoft without support from Untis themselves.
As they won't provide it, your only option is to log into Untis online using SSO and then use the code from your profile page to log into the app.
