### ISSUE TITLE
[Bug Report] Timetable moves one week forward, every time orientation is changed

### ISSUE THREAD

**Issue by SLH335** [SapuSeven/BetterUntis#406]
### Steps to Reproduce

1. Rotate your device in the timetable view
2. Observe, as the timetable moves one week forward

### Expected Result

When the device orientation is changed, the timetable should stay on the same week.

### Actual Result

The timetable moves one week forward, every time the orientation is changed, as shown in the video.

(Pay attention to the dates.)

https://github.com/SapuSeven/BetterUntis/assets/114884726/e4ecc089-066e-43e7-918d-a6df3abec3c3

### Android Version

Android 13

### BetterUntis Version

4.0.2 (28226820)

### Installation Source

GitHub Release

### Additional information

Similar to #314, but slightly different, as the view now moves forward one week, instead of returning to the current week.

**Comment by Lauritz-Tieste** [comment]
And similar to #360

**Comment by SapuSeven** [comment]
> And similar to #360 

Yes, this seems like the same issue
