### ISSUE TITLE
[Bug Report] #370 doesn't work in the latest beta version (4.0.2)

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SapuSeven/BetterUntis#407]
Unfortunately the error still occurs even though it was fixed by the PR.

### Android Version

Android 13

### BetterUntis Version

4.0.2 (28227720)

### Installation Source

GitHub Release

**Comment by SapuSeven** [comment]
Did you test the changes when you made the PR?
I myself haven't been able to replicate the issue at all, so I can't really help...

**Comment by Lauritz-Tieste** [comment]
Yes, I tested it and it worked perfectly

**Comment by SapuSeven** [comment]
That's weird.
Maybe we need an entirely different approach to control when the drawer can be opened.

**Comment by Lauritz-Tieste** [comment]
I'll take a look at it

**Comment by Lauritz-Tieste** [comment]
The changes are not included in the source code on the dev branch!

**Comment by SapuSeven** [comment]
Can't confirm.
I looked at the source code attached to the 4.0.2 release, as well as the current dev branch.
They both include the PR changes.

**Comment by Lauritz-Tieste** [comment]
The changes of 28968905a0922921316149c42be4c3ede2428cdb caused the error again

**Comment by Lauritz-Tieste** [comment]
>  I myself haven't been able to replicate the issue at all, so I can't really help...

To reproduce it: You have to quickly swipe in one direction on the timetable several times. Then the drawer should open

**Comment by SapuSeven** [comment]
Given [my comment in #408](https://github.com/SapuSeven/BetterUntis/pull/408#issuecomment-1703955143) - is it possible that this error happens when you (accidentally) start the swipe too far to the left edge?

**Comment by Lauritz-Tieste** [comment]
https://github.com/SapuSeven/BetterUntis/assets/84938977/74b3ff5d-b5c4-4b27-b823-b7314846e78f

**Comment by Lauritz-Tieste** [comment]
# Detailed description for #370, #407 and #408

## Steps to reproduce the error:
1. Open BetterUntis
2. QUICKLY swipe through the timetable (right/left), as if you wanted to quickly go 8 weeks into the future.

After a while, the NavigationDrawer accidentally opens on all of my devices.

For reproducing the error, it might be useful to test this on a real phone, rather than an emulator.

- Tablet (Samsung S6 Lite, BetterUntis Version 4.0.2, Android 13)
- Smartphone (Samsung A32, BetterUntis Version 4.0.2, Android 13)
---

> Given [my comment in #408](https://github.com/SapuSeven/BetterUntis/pull/408#issuecomment-1703955143) - is it possible that this error happens when you (accidentally) start the swipe too far to the left edge?

@SapuSeven No, this error also occurs if you only swipe in the middle of the screen and leave 2cm between swiping and the edge of the screen

**Comment by Lauritz-Tieste** [comment]
I was no longer able to cause the error in the latest version (4.1.0-beta-01 28334728).
