### ISSUE TITLE
[Feature Request] Add daily view

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#41]
**Describe the solution you'd like**
It would be nice to have the option to switch to a "daily view" because some schools have a lot of parallel lessons which makes the timetable hard to read.

<details>
  <summary><b>Additional context</b></summary>

  This option already exists in the original Untis app.
![Screenshot_20200125-112129](https://user-images.githubusercontent.com/36272047/73119626-dd483d80-3f64-11ea-95c4-c63e957065a8.jpg)

</details>

**Comment by SapuSeven** [comment]
You can enable this mode in _Settings -> General -> Week Display Settings -> Days to display_ since version 3.2.0 (currently still in Google Play Beta)

**Comment by Domi04151309** [comment]
Oh I'm sorry I didn't see that.
