### ISSUE TITLE
[Feature Request] Per app language support

### ISSUE THREAD

**Issue by Marco-9456** [SapuSeven/BetterUntis#410]
### Problem Statement

My phone language is German, but I want the app language to be English, and the app currently doesn't have the option to change its language.

### Solution Ideas

Last year, google added to android 13 Per-App Language Preferences, It lets users switch app languages from System settings, providing users with better control over their language choices for different apps, irrespective of the system language.

**Comment by SapuSeven** [comment]
Good idea - I added support for the System Per-App Language setting you mentioned in 974ad090c93ecf5ede971de2097ee0ce7b6aff07, it will be included in the next release.

**Comment by Marco-9456** [comment]
Thanks a lot ❤️‍🔥

**Comment by lm41** [comment]
@SapuSeven please have a look at #413.
This is improving this feature.
