### ISSUE TITLE
[Bug Report] Cannot Login

### ISSUE THREAD

**Issue by new-on-github** [SapuSeven/BetterUntis#412]
### Steps to Reproduce

Install app (4.0.2), scan QR-Code from website. 
Error:unexpected end of stream

### Expected Result

successful login

### Actual Result

Error:unexpected end of stream

no login

### Android Version

Android 13

### BetterUntis Version

4.0.2

### Installation Source

GitHub Release

### Additional information

Thanks for your work

**Comment by SapuSeven** [comment]
This is a known issue with the current networking library, which I haven't been able to figure out yet. It should work with another attempt though (hopefully).

**Comment by new-on-github** [comment]
Ok, scanning the QR-Code is not working.

But manual input of account data is working for me. Thanks a lot.

You can decide if you want to close it.

**Comment by ibndiaye** [comment]
Hey i tried doing both, so manual input but it wont let me login, what else could i try? Im running v4.0.2 from f-droid

**Comment by new-on-github** [comment]
> Hey i tried doing both, so manual input but it wont let me login, what else could i try? Im running v4.0.2 from f-droid

Did you use the password as key and not the token? The token from the QR-code didn't work for me.

**Comment by SapuSeven** [comment]
It got resolved directly via Matrix.
The trick was to use the QR-Code login and tick "Skip app secret resolution" under "Advanced settings" before logging in.
