### ISSUE TITLE
[Bug Report] "Authentication failed" wenn Konto mit App gekoppelt werden solll

### ISSUE THREAD

**Issue by rookie-ger** [SapuSeven/BetterUntis#414]
### Steps to Reproduce

1.) In WebUntis unter "Freigaben" den QR-Code mit BetterUntis scannen.

2.) In BetterUntis auf "Anmelden" klicken.
-> Authentication failed.

### Expected Result

Normale Anmeldung.

### Actual Result

Meldung: Authentication failed.

### Android Version

13

### BetterUntis Version

4.0.1 (28131459)

### Installation Source

Google Play

**Comment by lm41** [comment]
Duplicate of #412
