### ISSUE TITLE
[Bug Report]  class-timetables not fetched

### ISSUE THREAD

**Issue by cklif** [SapuSeven/BetterUntis#416]
### Steps to Reproduce

Log in and fetch information from the server.

### Expected Result

- classes' timetables show up n the corresponding view
- classes are displayed for every lesson in teachers' timetable-view

### Actual Result

- timetable-view for classes is empty
- in teachers' timetables the class is not displayed for any lesson
![975544c6-3fe7-41de-abf0-a843ced94b31](https://github.com/SapuSeven/BetterUntis/assets/63401214/7584d592-a1f3-45aa-bbd1-62c4918fb66a)
![d72b9911-c86a-4d9e-83b9-ead9a3cef6b0](https://github.com/SapuSeven/BetterUntis/assets/63401214/d180e11e-d47a-4b4d-b794-637585964da7)

### Android Version

14

### BetterUntis Version

4.0.2

### Installation Source

F-Droid

**Comment by SapuSeven** [comment]
Hi,
This is a know issue when Untis changes the elements when the school year changes.
To fix this, please use the button on the top right to edit your profile and login again. This will refresh all classes and other element metadata.
