### ISSUE TITLE
[Bug Report] Unable to use ARGB Values for Theme Colors

### ISSUE THREAD

**Issue by GangsterFox** [SapuSeven/BetterUntis#422]
### Steps to Reproduce

1. Go to Themes in Settings
2. Go to any Colors you want to change
3. Hit on Custom
4. Try to change the ARGB Hex

### Expected Result

It's supposed to accept those values and change the color using the ARGB Hex

### Actual Result

Upon hitting OK, the ARGB Hex does not apply and returns to it's default value before changing

### Android Version

Android 13 (OneUI 5.1)

### BetterUntis Version

4.0.2

### Installation Source

Google Play

### Additional information

Anything you add in the ARGB Hex box, does not get applied, even if it's a valid ARGB Hex.
I have also tried debug builds (4.0.2-DEBUG (28246151)), but that also didn't return with any improvement.
Using the custom color picker works completely fine and saves without any issues.
Using default Samsung Keyboard

**Comment by lm41** [comment]
Fixed with f66252de

**Comment by GangsterFox** [comment]
Thanks for putting out a fix! I'll build your branch tomorrow once I have time.
Once that is done, I will close this issue.
Thanks again!
