### ISSUE TITLE
[Bug Report] Missing translation

### ISSUE THREAD

**Issue by nautilusx** [SapuSeven/BetterUntis#43]
**Description**

4 missing strings for translation

<details>
These 4 strings from arrays.xml are not translatable.

`<string-array name="preference_schoolcolors">
		<item>For regular lessons</item>
		<item>For lessons with tests</item>
		<item>For irregular lessons</item>
		<item>For cancelled lessons</item>
</string-array>`

Any updates from weblate.org?

**Additional information**

 - Android version: 9.0
 - BetterUntis version: 3.2.1
 - Installation source: F-Droid

**Comment by SapuSeven** [comment]
Thanks.
Added in c26423febaa77ce5d9fd61a50f2118bd4447b185.
