### ISSUE TITLE
[UI Suggestion] Use outlined icons

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#44]
**Describe the solution you'd like**
A lot of apps started to use outlined icons. It would be nice if this app did as well, because they look cleaner and are often easier to recognize.

<details>
  <summary><b>Screenshots</b></summary>

![Screenshot_1579988970](https://user-images.githubusercontent.com/36272047/73127772-faf9bf00-3fc5-11ea-8911-c3d16e98c5fd.png)

![Screenshot_1579988982](https://user-images.githubusercontent.com/36272047/73127773-faf9bf00-3fc5-11ea-80f8-faae26b049f4.png)

</details>

**Comment by SapuSeven** [comment]
That looks really nice!
I'd like to get some more input, so please 👍 or 👎 for anyone else viewing this issue.

**Comment by Domi04151309** [comment]
Tell me when you have enough input so that I can create a pull request.

**Comment by SapuSeven** [comment]
Looks like you're good to go!

**Comment by SapuSeven** [comment]
Merged!
