### ISSUE TITLE
Teacher Name not updating

### ISSUE THREAD

**Issue by mosstuff** [SapuSeven/BetterUntis#442]
### Steps to Reproduce

Go onto a lesson and note down the teachers name
Now, go into the official app and see it there.

### Expected Result

The names Match.

### Actual Result

The names do not match

### Android Version

Android 13

### BetterUntis Version

4.0.1

### Installation Source

Google Play

### Additional information

My teacher married and changed their name so they changed it in this too. The official app shows it Better Untis doesnt
![Screenshot_20231221-071828](https://github.com/SapuSeven/BetterUntis/assets/68462312/078cd549-98d2-489c-8f92-54492193b87e)
![Screenshot_20231221-071837](https://github.com/SapuSeven/BetterUntis/assets/68462312/e5b33bb2-1c30-4701-9570-f1d8def392d2)

**Comment by SapuSeven** [comment]
Please update the timetable master data manually by selecting the profile icon at the top right -> edit profiles -> (tap your profile) -> login.
This should refresh the timetable data.
