### ISSUE TITLE
[Request] Fastlane File Structure

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#48]
It would be great if this project had the Fastlane file structure for its F-Droid store listing. This would enable you to edit the title, description and screenshots of your app without having to open a merge request every time.

To make a pull request I would need up to date screenshots and a description because the description on F-Droid and the one on the Play Store are not the same.

**Comment by SapuSeven** [comment]
I uploaded the current screenshots here: https://imgur.com/a/j2vNafG

**Comment by Domi04151309** [comment]
- [x] Establish Fastlane file structure
- [x] Publish release with file structure
- [x] Notify F-Droid [`fdroid/fdroiddata!6508`](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6508)

**Comment by Domi04151309** [comment]
The fastlane file structure is not yet present in a release. This is really strange since the commit is included in v3.2.2.
