### ISSUE TITLE
Display Homework

### ISSUE THREAD

**Issue by Jan200101** [SapuSeven/BetterUntis#5]
Being able to see Homework like in the proprietary Untis app would be neat

**Comment by SapuSeven** [comment]
It should already show up in the lesson details dialog. Or do you mean a separate overview of all homeworks?
 ![](https://i.imgur.com/oD81Acg.jpg)

**Comment by Jan200101** [comment]
Oh, I wasn't even aware that was a thing because I am so used to a little icon being displayed in the official app and this not being the case in BU-Legacy

**Comment by SapuSeven** [comment]
Glad it works.

I will likely implement this little icon in the future.
