### ISSUE TITLE
[Feature Request] Show breaktime supervision in timetable

### ISSUE THREAD

**Issue by new-on-github** [SapuSeven/BetterUntis#53]
Breaktime supervisions are not shown in the teachers timetable. It would be nice to implement this.

Thanks for your amazing work so far.

**Comment by SapuSeven** [comment]
This should already be working since version [3.2.2](https://github.com/SapuSeven/BetterUntis/releases/tag/v3.2.2). Please check if you are using the latest version.

**Comment by new-on-github** [comment]
Thanks a lot, this works for me now!
