### ISSUE TITLE
[Bug Report] Crashes  choosing class

### ISSUE THREAD

**Issue by 7RST1** [SapuSeven/BetterUntis#57]
**Description**

App crashes after selecting class. This is how I made it crash;
1. Log in with 1346600 and anonymous account
2. Choose Classes in Navigation menu.
3. Choose 1STA in the list. App crashes

Edit:
Just experienced the same type crash when selecting room also. Another Norwegian school has the exact same issue; ID 1416900
<details>
  <summary><b>Screenshots</b></summary>

  
![Screenshot_20200209-185501](https://user-images.githubusercontent.com/16783057/74107179-cbbe8280-4b6d-11ea-8aad-f7e815e9764a.jpg)

</details>

<details>
  <summary><b>Logs</b></summary>
Copy button doesn't seem to work the brief moment the crash log appears, so a screenshot is attached above.

Extracted from image above:
kotlinx.serialization.json.JsonParsingException:
Invalid JSON at 391: Expected '[, kind:
kotlinx.serialization.StructureKind$LIST@d4c9465'

at
kotlinx.serialization.json.internal.StreamingJsonlnput
begin Structure(Streaming Jsonl put.kt:116)

at
kotlinx.serialization.internal.AbstractCollection
Serializer.patch(Collection Serializers.kt:41)

at
kotlinx.serialization.internal.AbstractCollectionSeriali
zer.deserialize(Collection Serializers.kt:61)

at
kotlinx.serialization.json.internal.Polymorphic.deco
de Serializable Value Polymorphic(Polymorphic.kt:33)

at

kotlinx.serialization.json.internal.Streaming Jsonlnput
.decodeSerializableValue(Streaming Jsonl put.kt:29)
at
kotlinx.serialization.ElementValueDecoder.decodeSer
ializableElement(ElementWise.kt:142)

at
com.sapuseven.untis.models.untis.timetable PeriodT
ext$$serializer.deserialize(Unknown Source:101)

at
com.sapuseven.untis.models.untis.timetable.PeriodT
ext$$serializer.deserialize(PeriodText.kt:6)

at
kotlinx.serialization.json.internal.Polymorphic.deco
de Serializable Value Polymorphic(Polymorphic.kt:33)

at
kotlinx.serialization.json.internal.Streaming Jsonlnput
decodeSerializableValue(Streaming Json input.kt:29)
at
kotlinx.serialization.ElementValueDecoder.decodeSer
ializableElement(ElementWise.kt:142)

at
com.sap seven.units.models.untis.timetable. Period
Serializer.deserialize(Unknown Source:243)

at
com.sap seven.units.models.untis.timetable. Period
Serializer deserialize(Period kt:7)
</details>

**Additional information**

 - Android version: 10
 - BetterUntis version: 3.2.2-DEBUG+18.319
 - Installation source: SapuSeven.com

**Comment by 7RST1** [comment]
Tried to debug, myself. I'm not that good with Android Studio tho.
It looks like it tries to get JSON from https://mobile.webuntis.com/ms/app/1346600?m=getTimetable2020Body , but either times out or receives the JSON but it only contains an error message.

**Comment by SapuSeven** [comment]
I'm sorry you encounter so many problems.
Please check out 0e53fccbfccb495f06802e15f304d998b99c9d21 ([build#329](https://sapuseven.com/app/BetterUntis/api.php?q=download&variant=debug&id=329)), it should fix the crash.

**Comment by 7RST1** [comment]
It works! One last thing tho. I can't access the Personal tab or Teacher tab in the app. It seems to work on WebUntis. Teacher tab doesn't show anything and clicking Personal tab closes the dialog. @SapuSeven
