### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by phibr0** [SapuSeven/BetterUntis#58]
There is an option called "anzuzeigende Stunden" in German and I want to know what it does.
![Screenshot_2020-02-10-16-23-18-966_com sapuseven untis](https://user-images.githubusercontent.com/59741989/74162856-bd31a300-4c21-11ea-9630-3ec98d2a56c1.jpg)

**Comment by SapuSeven** [comment]
You can input a range of hour indices to reduce the number of displayed hours, for example `1 to 8` to only show the first eight hours in the timetable.

**Comment by spaetz** [comment]
Uhh, sorry. But even with your explanation I am unsure what's the right format for this textfield. Would I enter 8? 1-8? 1,2,3,4,5,6,7,8? Or literally '1 to 8'?

**Comment by SapuSeven** [comment]
You can write `1-8`, `1 to 8`, `1 bis 8`, basically two numbers with some separator.
But you're right, I should probably add an explanation for this preference.
