### ISSUE TITLE
[Bug Report] App crashes instantly (JSON parsing error?)

### ISSUE THREAD

**Issue by konradmoesch** [SapuSeven/BetterUntis#59]
**Description**

_BetterUntis instantly crashes when I try to open it. Because of the crash, I can't see any error message. But a friend sees a JSON parsing error_

<details>
  <summary><b>Logs</b></summary>

  _I could try add a more detailed log later, if needed_
</details>

**Additional information**

 - Android version: _10_
 - BetterUntis version: _3.2.2_
 - Installation source:  _F-Droid_

**Comment by SapuSeven** [comment]
Please wait for the next release which will do a better job at collecting error information.

**Comment by SapuSeven** [comment]
Can you install the [debug build from the crash-reporting banch](https://334-180734070-gh.circle-artifacts.com/0/outputs/apk/debug/app-debug.apk) and see if you get any more useful information about the crash?

**Comment by sedding** [comment]
Hej, 
I was able to reproduce the error within the debug-built. This is the error message. 

<details>
<summary>Crash Log</summary>

```
Anfragen-ID: 15
Fehlercode: 3
Fehlermeldung: Invalid JSON at 4234: Expected string or non-null literal
```
</details>

The error first occurred when trying to show the schedule of several specific teachers/classes. The it occurs at startup - I estimate because the app tries to reload the schedule...?

Thank you for your great software.
Michael

**Comment by SapuSeven** [comment]
Can't say much about what exactly causes the crash. Does this also happen with anonymous access? In that case you could send me the school id so I can have a look at it

**Comment by konradmoesch** [comment]
For me, the JSON line differs, but I think this line won't be helpful for you.
My school unfortunately does not allow to view any timetable with anonymous login..
But I found out that this issue is not effecting the whole timetable: next week is shown fine for me, but this week throws the error. Also, the notification in breaks is working fine (sometimes)

Edit: this issue is gone for me in the latest version (3.3)

**Comment by SapuSeven** [comment]
As mentioned, 3.3 should have fixed this.

After you update to 3.3.1, please look in _Settings->General->View logged errors_ to see if there are any messages regarding this issue.

**Comment by sedding** [comment]
Sounds good. I'll confirm that when the new release ist deployed via FDroid.

**Comment by SapuSeven** [comment]
I'm going to assume that this issue is resolved.
