### ISSUE TITLE
Subjects multiply on refresh

### ISSUE THREAD

**Issue by Jan200101** [SapuSeven/BetterUntis#6]
![](https://i.imgur.com/GH8rI35.jpg)
![](https://i.imgur.com/vePdyWC.jpg)
Every time I reload the timetable this one day keeps duplicating it's subjects

**Comment by SapuSeven** [comment]
Thanks for reporting!
This happens because of a bad implementation of monthly loading.
I am already working on an updated week-based loading system.

**Comment by SapuSeven** [comment]
I just implemented week-based loading.

The timetable should refresh correctly now, plus you get to see the last update in the bottom left corner.

**Comment by Jan200101** [comment]
fixed
