### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by lukasl-dev** [SapuSeven/BetterUntis#60]
<details>
<summary>Crash Log</summary>

```
Anfragen-ID: 8
Fehlercode: 2
Fehlermeldung: Read error: ssl=0x6f88ae4c88: I/O error during system call, Connection reset by peer
```
</details>

**Comment by SapuSeven** [comment]
You can basically treat this as a Network Error. Reloading the timetable should work fine.

**Comment by SapuSeven** [comment]
Closing as inactive and probably not relevant
