### ISSUE TITLE
[Bug Report]  Multi-hour lessons not merged any more

### ISSUE THREAD

**Issue by phibr0** [SapuSeven/BetterUntis#63]
**Description**
Now everything is splitted

[logs-1583357588910.zip](https://github.com/SapuSeven/BetterUntis/files/4289793/logs-1583357588910.zip)
[logs-1583342047681.zip](https://github.com/SapuSeven/BetterUntis/files/4289794/logs-1583342047681.zip)

Here are two logs from different Times.

![Screenshot_2020-03-04-22-32-00-816_com grupet web app](https://user-images.githubusercontent.com/59741989/75924870-fe575480-5e67-11ea-87ab-5c4f5c04073d.jpg)
![Screenshot_2020-03-04-22-30-20-691_com sapuseven untis](https://user-images.githubusercontent.com/59741989/75924871-feefeb00-5e67-11ea-8556-7adfac077b52.jpg)

**Additional information**

 - Android version: 10
 - BetterUntis version: 3.3 i think (the newest)
 - Installation source: Google Play

**Comment by phibr0** [comment]
I would like a function to deactivate the error messages .. I keep getting several and the window below is annoying. How about a debug mode?

**Comment by SapuSeven** [comment]
Good idea.
I'll start working on that.

**Comment by SapuSeven** [comment]
16f91392b62765f36084bd2102871930bd049e1a fixes multi-hour-lessons.
Next version will be released to beta today or tomorrow.

**Comment by Domi04151309** [comment]
Is this already released to beta?

**Comment by SapuSeven** [comment]
Not yet, planning to release a fix in about an hour

**Comment by SapuSeven** [comment]
Beta Update live in Google Play.
