### ISSUE TITLE
[Error Report]

### ISSUE THREAD

**Issue by ghost** [SapuSeven/BetterUntis#64]
<details>
<summary>Crash Log</summary>

```
Unknown JSON object "attachments" encountered, value: []

```
</details>

**Comment by SapuSeven** [comment]
Thanks, this will be addressed in the next Beta update

**Comment by SapuSeven** [comment]
004827b72434f9de615f65d6254b500e8c7c3a55 will suppress those errors.
Available in the next beta release.
