### ISSUE TITLE
[Bug Report] weekly scrolling not working properly?

### ISSUE THREAD

**Issue by konradmoesch** [SapuSeven/BetterUntis#65]
**Description**

_I´m not sure whether this is a bug, but I think so:
If you change the number of days to show (In German: "Anzuzeigende Tage"; not the length of the week in general), you will skip some days when scrolling._

Example:
- change the number of days to show to 3
- you can see Monday to Wednesday
- scroll to the next days
Expected behaviour: you should see the next three days (Thursday, Friday and again Monday)
But you see Monday to Wednesday of the next week, so 2 days are skipped

Maybe this behaviour is intended, but i would change weekwise scrolling to use the number of days shown on screen to make it more usable in such a case

There are some errors thrown when using the custom amount of days to show.

[logs-1583434599340.zip](https://github.com/SapuSeven/BetterUntis/files/4294612/logs-1583434599340.zip)

**Additional information**

 - Android version: _10_
 - BetterUntis version: _3.3_
 - Installation source: _Sapuseven.com_

**Comment by SapuSeven** [comment]
This is actually a desired behavior. You can enable "Snap to days" ("Tageweise scrollen" I think) to view the rest of the week.

**Comment by konradmoesch** [comment]
but what´s the difference then between using monday to wednesday in "custom week range" which does not schow thursday and friday for example or using "days to display" = 3 and  weekwise scrolling which skips these days?
Also the error I found when changing "days to display" (I attached the zip in the first post) isn´t intended ;)
(_The error says "Unknown JSON object "attachments" encountered, value: []_)

**Comment by SapuSeven** [comment]
Oh now I get what you mean.. yeah, scrolling by screens instead of weeks does make more sense.

**Comment by SapuSeven** [comment]
WeekView scrolling and corresponding settings have been changed since this issue was opened.
Please open a new one if you still have problems.
