### ISSUE TITLE
[Feature Request] Default Classes / Bookmarks for sidebar

### ISSUE THREAD

**Issue by steelstrings** [SapuSeven/BetterUntis#66]
Since the personal timetable is incomplete at times, I would prefer an easy access to the timetable of the class I attend. Instead of always having to look (/search) for the class I need, I would prefer it to be able to bookmark classes (maybe also rooms / teachers) you want and add an entry to the sidebar.

[This has also been requested in the OpenUntis issues (as it still was active).](https://github.com/Perflyst/OpenUntis/issues/14)

**Comment by konradmoesch** [comment]
My school does not have personal users for everyone, so there is only one user per class.
There are some classes at the same time, when the class is split into courses.
There, I would like a filter feature, too. So that we are able to hide classes with eg. a certain teacher or so.

**Comment by SapuSeven** [comment]
You can change the personal timetable in the settings to display a class instead, if that helps

**Comment by steelstrings** [comment]
Then accessing my personal timetable doesn't seem to be possible (without reverting this particular setting). I personally would want easy access to both. Since I'm not sure of the differences between both timetables. If I remember correctly, the class timetable also lacks things sometimes (or at least used to). Besides my (real) personal timetable is cleaner since it doesn't show lessons, I'm not enrolled in.

**Comment by DreamyLynn** [comment]
Working on this.

**Comment by SapuSeven** [comment]
Bookmarks were implemented in #241
