### ISSUE TITLE
[Feature Request] Untis Messenger Shortcut

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#68]
**Describe the solution you'd like**

It would be nice to have a shortcut to the Untis Messenger app in the nav menu when the app is used by the school.
This might require more network traffic analysis.

**Comment by Domi04151309** [comment]
<img src="https://user-images.githubusercontent.com/36272047/76680885-1d36b300-65ed-11ea-8bf6-d6444e93181f.jpg" width="200"/>


This seems to indicate that the school uses Untis Messenger

**Comment by SapuSeven** [comment]
Unfortunately I have no idea how the untis messenger works as my school doesn't use it.

**Comment by Domi04151309** [comment]
So apparently the Untis messenger is just a rebranded version of Grape

https://chatgrape.com/doc/deployment/clients.html

**Comment by Domi04151309** [comment]
I am currently searching for a method to only show the entry when the messenger is used by the school by checking for a messenger channel value in responses in MainActiviy.
