### ISSUE TITLE
[Bug Report] Info Center Links and Attachments

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#69]
**Description**

Links in the info center messages tab get highlighted but are not clickable.

<details>
  <summary><b>Screenshots</b></summary>

  
![Screenshot_20200312-071107](https://user-images.githubusercontent.com/36272047/76492501-b1a7e680-6430-11ea-91bb-55341e78161b.jpg)

</details>

 - Android version: _10_
 - BetterUntis version: _3.3.1 (20)_
 - Installation source: _Google Play_

**Comment by Domi04151309** [comment]
Also attachments are not downloadable/don't show up.

Attachments are available for "Kurzanleitung Messenger"

| BetterUntis | Untis Mobile |
|---|---|
| ![Screenshot_20200314-105442](https://user-images.githubusercontent.com/36272047/76679634-6c2b1b00-65e2-11ea-8f92-e9a14dc220f2.jpg) | ![Screenshot_20200314-105456](https://user-images.githubusercontent.com/36272047/76679640-7816dd00-65e2-11ea-8645-ff43fe5faf82.jpg) |

**Comment by SapuSeven** [comment]
Can you please take a look at _BetterUntis Settings -> general -> view logged errors_ and see if there are any entries regarding message attachments?

**Comment by Domi04151309** [comment]
There are no entries regarding message attachements.

**Comment by Domi04151309** [comment]
<img src="https://user-images.githubusercontent.com/36272047/81720589-e828ce80-947e-11ea-834f-ff4285585ca0.jpeg" width="200" />

I am currently working on enabling attachments.

**Comment by SapuSeven** [comment]
Links fixed in a0f63b3d1cc562a9c3aa2cf22688f1aa13788685, attachments implemented in #74.
