### ISSUE TITLE
[Feature Request] Long Teacher Names in Dialog

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#71]
**Describe the solution you'd like**

Show long teacher names in detailed lesson dialog because it's more detailed.

<details>
  <summary><b>Additional context</b></summary>

| Screenshot | Description |
| --- | --- |
| ![That's a big picture!](https://user-images.githubusercontent.com/36272047/81079050-50ac0480-8eef-11ea-8a2b-71b37734089c.jpeg) | Currently the short teacher name is displayed. |

</details>

**Comment by SapuSeven** [comment]
Good idea!

**Comment by SapuSeven** [comment]
#73 merged.
