### ISSUE TITLE
[Request] Boolean Preference UX

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#72]
**Describe the solution you'd like**

I have realized that the app mostly uses checkboxes for true/false values where it would make more sense to use toggle switches. I wanted to know what you think about this.

<details>
  <summary><b>Additional context</b></summary>

  An article that explains this in more detail.
 [Checkbox vs Toggle Switch - UX Planet](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8)
</details>

**Comment by SapuSeven** [comment]
I did some research and think it would indeed make sense to use toggle switches.
This is pretty low priority tho, so anyone is welcome to implement this.
