### ISSUE TITLE
[Request] Text Legibility

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#75]
**Describe the solution you'd like**

Currently, the app bar title and the titles of the week view have the same thickness. To better show title hierarchy the week view titles should be less bold than the app bar title.

Also, the timestamps should use the secondary text color for better contrast to the titles.

| Bold Text | Semi Bold Text |
|---|---|
|  ![2](https://user-images.githubusercontent.com/36272047/81842488-5edfcd80-954c-11ea-9c01-c58620b8dbb7.jpeg) | ![semi](https://user-images.githubusercontent.com/36272047/81842505-67d09f00-954c-11ea-9cbf-54ef31b79fbb.jpeg) |

**Comment by Domi04151309** [comment]
I will create a pull requests when @SapuSeven approves this.

**Comment by SapuSeven** [comment]
Looks good, I'd be happy to approve your PR
