### ISSUE TITLE
[Request] Improve App Icon

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#81]
**Describe the solution you'd like**

Pixel perfectly centered things don't always seem centered to the human eye. The launcher icon does seem a little bit too far at the top right. I'd suggest centering it in a way that it also appears centered.

![ic_launcher](https://user-images.githubusercontent.com/36272047/83140365-40520880-a0ee-11ea-97f3-742ed485d500.png)

The top one is the current app icon and the bottom one a more centered looking one.

**Comment by SapuSeven** [comment]
Thanks, that really looks better.
I suppose you are ready to create a pull request? I'd happily merge it.
