### ISSUE TITLE
[Feature Request] Widgets and Shortcuts

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#88]
**Describe the solution you'd like**

There kind of is some unused code already in the app and a widget would be nice.

- [x] Timetable
- [x] Daily Messages
- [x] Timetable Link

**Comment by SapuSeven** [comment]
Yes, I already thought about implementing such features.
However, I currently only have time to work on the app during the weekend.

**Comment by Domi04151309** [comment]
I will take a look at it.

**Comment by Domi04151309** [comment]
I have created a decent looking widget for displaying the messages of the day but I don't know how to get the messages yet. you can take a look at the [`widgets`](https://github.com/Domi04151309/BetterUntis/tree/widgets)-branch if you want.

#### Here's a little preview:
<img src="https://user-images.githubusercontent.com/36272047/86536645-8cf8e280-bee9-11ea-9ba8-1700858b0c23.jpg" width="200" />

**Comment by SapuSeven** [comment]
Thank you very much for taking a look at it. The image you sent already looks promising.
As I mentioned, I don't have much free time, but I will try my best to help you if there are any questions, just contact me.

**Comment by Domi04151309** [comment]
I have implemented a base widget class for the easy creation of further widgets and waiting for my school to post something in the daily messages so that I can implement the code. I'd go with a ListView because widgets only support simple view types and that might be the best option. For the timetable widget, I'd suggest a similar approach as with the watch app.

**Comment by Domi04151309** [comment]
<img src="https://user-images.githubusercontent.com/36272047/87834497-def71c00-c88a-11ea-838d-03f96dc6740e.jpg" width="200" />

I am using a TextView with spans now because ListViews in widgets are too complicated. The timetable widget is already working now but might need a new design. A messages widget will be next. (And maybe a timetable shortcut)

**Comment by Domi04151309** [comment]
@SapuSeven what is the easiest way to get the name associated with the `PeriodElement` returned by the `ElementPickerDialog`?

**Comment by Domi04151309** [comment]
Ok I found out that the following works:
```
timetableDatabaseInterface?.getShortName(element?.id ?: return, TimetableDatabaseInterface.Type.valueOf(element.type))
```

**Comment by SapuSeven** [comment]
Merged and published. Thanks for your contribution!

**Comment by Domi04151309** [comment]
I have realized that lesson don't get merged yet.

**Comment by SapuSeven** [comment]
True, but honestly I'd rather wait for the new backend-frontend-separated system (#87) instead of duplicating even more code. It seems that would make things way easier.

**Comment by Domi04151309** [comment]
You're right. When will you be ready with the teacher specific features? I don't want to cause extra work with open pull requests.
