### ISSUE TITLE
[Feature Request] Daily Messages Unread Dot

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#96]
**Describe the solution you'd like**

Display a dot on the menu icon when there are unread info center messages available.

This will work by saving the size of the list to the shared preferences every time you open the info center. Then every time the timetable is loaded it will also load the messages and check if the list size is greater than the saved size. If so it will display the dot to inform the user that there are new unread messages in the info center.

**Comment by SapuSeven** [comment]
Merged with #114.
